### PR TITLE
(Feature) Cookies warning

### LINKED ISSUE #180: [UI/UX] Cookie Policy accept
Implement https://zpl.io/2ynmnjq

It's the Gnosis standard confirmation form.

**Note:** There are no analytics or anything yet, but there surely will be.

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #180 

It currently supports Google Analytics only, just add `REACT_APP_GOOGLE_ANALYTICS_ID='your-id-here'` to `.env`

If there's no `REACT_APP_GOOGLE_ANALYTICS_ID` in `.env` it shouldn't show anything (useful for disabling this component).

- **X** button closes the message and lets the user to navigate without it interfering, but the message will be visible again when the app is reloaded.
- _"Accept Cookies"_ does just that. The message won't appear again unless the browser's cookies are wiped by the user.

It should look like this:

Screen Shot 2020-09-21 at 16 58 08

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr300--conditionaltokensexplorer.review.gnosisdev.com

**Review by mariano-aguero — APPROVED** [review]
LGTM

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr300--conditionaltokensexplorer.review.gnosisdev.com

**Review by hpmaxi — APPROVED** [review]

**Comment by elena-zh** [comment]
@gabitoesmiapodo 
The only thing I can check here is that REACT_APP_GOOGLE_ANALYTICS_ID='your-id-here' is added  to .env (according to the code)
However, I cannot find the confirmation form even when I open the app in an incognito tab. 
As there are no analytics or anything yet for the app, how can I test the current changes?

**Comment by gabitoesmiapodo** [comment]
@elena-zh I think it has to be added manually to Netlify's settings.

I don't know how to do it, @mariano-aguero any ideas?

**Comment by elena-zh** [comment]
@gabitoesmiapodo , Accept Cookies button is shifted on the form. Can you fix it, please?

**Comment by gabitoesmiapodo** [comment]
@elena-zh Sure, where are you testing this? It may be another built version problem.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , Chrome,  Version 85.0.4183.121 (Official Build) (64-bit)
The current screen resolution is 1536x712. 100% scale

**Comment by gabitoesmiapodo** [comment]
@elena-zh Should be fixed here https://github.com/gnosis/conditional-tokens-explorer/pull/324

**Comment by elena-zh** [comment]
@gabitoesmiapodo , I have verified the changes in #324. Looks good to me.

**Pull request merged**
