### PR TITLE
[FE] - Redeem position

### LINKED ISSUE #28: [FE] - Redeem position
**Page:**
https://www.figma.com/file/W3hK57rQTH2A6TXrHxYQQh/Contidional-Tokens-Explorer?node-id=8%3A32

**Notes:**
- Manually enter raw positionId
    - Validate Position exist
    - Validate user has position balance
- Manually enter raw conditionId
    - Validate condition exist
    - Validate condition is resolved
    - Validate condition is included on Position conditions set
- Calculate parentCollection
- Show preview
- Submit

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #28 

- [x] Manually enter raw positionId
- Validate Position exist
- Validate user has position balance
- [x] Manually enter raw conditionId
- Validate condition exist
- Validate condition is resolved
- Validate condition is included on Position conditions set
- [x] Calculate parentCollection
- [x] Show preview
- [x] Submit

Position String Details:
- Cond1 - outcomesSlotCount: 2
- Cond2 - outcomesSlotCount: 3

- Spliting Cond1 from DAI generates following 2 positions:
    - Pos1 = DAI C:Cond1 O:1 -> 0:1 comes from indexset 0b01
    - Pos2 = DAI C:Cond1 O:2 -> 0:2 comes from indexset 0b10

- Spliting Cond2 from Pos1 generates following 3 (for now only trivial partition) positions:
    - Pos3 = DAI C:Cond2 O:1 C:Cond1 O:1
    - Pos4 = DAI C:Cond2 O:2 C:Cond1 O:1
    - Pos5 = DAI C:Cond2 O:4 C:Cond1 O:1

- Redeeming x10 Pos1 when Cond1 is resolved with [1, 0] should generate the following Redeemed Preview:
    - 10 DAI

- Redeeming x10 Pos3 when Cond3 is resolved with [0.5, 0.25, 0.25] should generate the following Redeemed Preview:
    - [DAI C:Cond1 O:1] x 5

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr41--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr41--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr41--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr41--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr41--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr41--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gabitoesmiapodo** [comment]
Ugh, sorry for the conflicts. Ping me if you need help with those...

**Comment by hpmaxi** [comment]
@gabitoesmiapodo Can you check that everything is in place?

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr41--conditionaltokensexplorer.review.gnosisdev.com

**Pull request merged**
