### PR TITLE
Improve details of conditions and positions

### LINKED ISSUE #355: [FE] Add more information to condition and position details
In [this issue](https://github.com/gnosis/conditional-tokens-explorer/issues/340), I mentioned a few columns that would be great to add to the list views.

That information should also be added to the details view.

In the conditions details, we should add:
- creation date
- creator address
- Total Value Locked
- Link to any Omen markets for this condition
- Resolution details (for conditions that have been resolved)

In the positions details, we should add:
- creation date
- oracle address / name
- question ID
- total value locked
- Collateral token address
- Wrapped outcome token address
- Resolution details (for positions whose conditions have been resolved)

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #355, also fixed a minor bug on modals for oracles/questions where the external link pointed to `.../undefined` 

Some fields were already there. Links to Omen markets are going to be addressed in #356 . Resolution details and TVL weren't added, they are extracted in another issue #526 that need a design (UX/UI) and confirmation about the feasibility of TVL with the current schema.

### CODE REVIEW

**Review by gabitoesmiapodo — CHANGES_REQUESTED** [review]
Nice.

- "Create Date" should be "Creation Date"
- "Creator" should be "Creator Address"

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr527--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — APPROVED** [review]
🦘

**Review by mariano-aguero — APPROVED** [review]

**Comment by elena-zh** [comment]
Verified. 
Several minor issues are found: 
#538 Display oracle = realit.oi for a position when it belongs to an omen condition
#539 Show a question text instead of a question id on a positions/conditions lists for Omen condition

**Pull request merged**
