### PR TITLE
[FE] Change how the Condition ID is displayed in Position Details

### LINKED ISSUE #379: [FE] Change how the Condition ID is displayed in Position Details
Related to https://github.com/gnosis/conditional-tokens-explorer/pull/372#pullrequestreview-497788103

It seems that in the vast majority of cases we're getting only one Condition ID for the Position Details section.

So to make this look a little less cluttered I propose:

- Remove the table.
- Use the regular title / value pattern (Condition ID / condition id hash, which should be a link to the related Condition Details section, and don't forget the "copy" button).
- If there's more than one condition id (which seems to be rare, but it could happen), add a "more..." link, which should open a modal window with a table displaying all the condition IDs there are for the position.

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #379 

Some positions IDS with 2 or 3 conditions

0x573ac9fcf1e16ebf15fb2779ca54153a3cec8582d28d5d56210d1228cf6ec781
0xbf96e5419a5ddfa8ed7846252ab262e7a23bf46a4b9782d9cc7f05e3c6705b0a
0x5647c5cb905ecbacc9aa97d7954da4e358da04b4c9cecdadd2fdb827bb215fd1

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr422--conditionaltokensexplorer.review.gnosisdev.com

**Review by hpmaxi — APPROVED** [review]

**Comment by mariano-aguero** [comment]
Look like this
Screenshot_20201005_164038

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr422--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — CHANGES_REQUESTED** [review]
Works just fine, but I'd suggest using a text link instead of a button.

Something a few px smaller than the regular text, underlined (no underline on mouse hover) would be OK.

**Comment by mariano-aguero** [comment]
> Works just fine, but I'd suggest using a text link instead of a button.
> 
> Something a few px smaller than the regular text, underlined (no underline on mouse hover) would be OK.

Look like this
Screenshot_20201006_100630

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr422--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr422--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — APPROVED** [review]
Added a few changes, everything looks fine.

**Pull request merged**
