### PR TITLE
Fix moment/UTC use

### LINKED ISSUE #502: Positions/Conditions lists: creation date filter shows positions that were created on 'the selected day - 1'
See the pic: 

The issue is reproducible for the filters on the  Positions and Conditions lists

### LINKED ISSUE #713: Filtering by the same date can show different results
**Steps:** 

1. open conditions list (or positions list)
2. open filter's bar
3. select from date = today (or any other)
4. select to date = today (or any other)
5. run the search
6. open the filter and select from date = today (the same as it is in the filter), run search

**AR:** grid shows another quantity of the search results
https://drive.google.com/file/d/1hVWVyS959gWIAdZVnvnZSHw8moelkgYW/view

**ER:** search results should be the same

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #502 
Closes #713

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr843--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
Hey @hpmaxi , the issue is still reproducible for me=( 



If it may help, my time zone is UTC+3

**Comment by hpmaxi** [comment]
@davidalbela Can you check it too? If it works we can merge the pull request and close both issues.

**Review by davidalbela — APPROVED** [review]
Hi Maxi! LGTM

**Pull request merged**
