### PR TITLE
Add partition again

### LINKED ISSUE #226: [FE] Add "Partition / Collections" list to Position Details
Design: https://zpl.io/2GZznJ9

It makes no sense having all the "Edit Partition" functionality if we are not able to see the partition later...

This should be done after #66 and #67 are finished and merged.

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #226 

I need to test it better and compare the preview with the one shown in split but to do this I have to be able to create positions or have a position from a non-trivial partition.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr262--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr262--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr262--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr262--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr262--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — CHANGES_REQUESTED** [review]
It looks fine.

Maybe change the height for the "Partition / Outcomes Collection" list? It seems it's always the same height (1 row).

I think that adding the prop `height="auto"` should do it.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr262--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — APPROVED** [review]

**Review by mariano-aguero — APPROVED** [review]

**Pull request merged**
