### PR TITLE
Pass filter to usePositionsList to only show positions with balance

### LINKED ISSUE #750: Add toggle filter to list positions with balance

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #750
That is what Auryn asked in the last sync. Is just a client-side filter function passed to the actual hook for positions. 

Maybe we can use that kind of filtering for everything but is not a big improvement if we continue using 'no-cache', because we will need to fetch everything in sections where the query narrows the result. Doing this full fetch only once seems fine but in each positions fetch can be a problem right now.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr751--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
HI @hpmaxi , the filtering looks good to me. 
Several questions from my side are related to the design. 
It seems to me, that it would be better to align 'With Balance' option according to the rest elements on the bar (left-aligned). 
to the left

May be, to add more descriptive label to it.. Something like 'Show positions with balance only' or so... and apply to if styling which will correspond to the rest filter elements on the bar.. 
However, I'm not sure. May be, @gabitoesmiapodo has better vision how the toggle should look like..

**Comment by gabitoesmiapodo** [comment]
@elena-zh 

Agreed.

@hpmaxi 

I think using a select like the rest of the filters would be more appropriate. 

You could use something like:

**Title:** With Balance
**Options:** All / Yes / No

Also: I don't know how important this filter is, but maybe put it after the existing ones (at the bottom)?

**Review by gabitoesmiapodo — CHANGES_REQUESTED** [review]
See https://github.com/gnosis/conditional-tokens-explorer/pull/751#issuecomment-742481612

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr751--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
The changes look good to me now.

**Review by gabitoesmiapodo — APPROVED** [review]
giphy-downsized

**Review by mariano-aguero — APPROVED** [review]

**Pull request merged**
