### PR TITLE
(Fix) Margins

### LINKED ISSUE #628: UI - double margin between CREATOR ADDRESS and REPORTING ADDRESS sections on a custom reporter condition details
See the pic: there is a double margin 20 px between CREATOR ADDRESS and REPORTING ADDRESS sections

**Expected result:** 1 margin = 20 px.

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #628

Specifically https://github.com/gnosis/conditional-tokens-explorer/issues/628#issuecomment-734866188

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr695--conditionaltokensexplorer.review.gnosisdev.com

**Review by elena-zh — APPROVED** [review]
The changes look good to me. 
However, now the question text section for an Omen condition's position is missing. 
I have reopened the #622 bug for this case

**Comment by gabitoesmiapodo** [comment]
@elena-zh I'd need examples for every possible condition / position so I don't miss one.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , here are the examples: 

1. Omen condition without Omen markets   0x00af9b2462e40e7d04678054e1f734dbd1f2c0ceb6af6a79ea3cba7fa3ac9ae7
2. Position for an Omen condition without Omen markets   0x737cc723f157ca3555ce554f3ceb8f4a415e3a91b30336f3a780378052e440b63. 
-----------------------------
1. Omen condition with Omen markets 0xb3e84dbd55f0846de0a37b5a1010f5ad10d78f6d60b07519da6377ef939290fc
2. Position for an Omen condition with Omen markets 0x906983556f829dafd2d82800abd2e050d3bffabec1c51ed837ae3a9ce9959511
------------------------------
1. Custom reporter condition 0x4621c84fb3bd26b461a77b1201ff0d009e3dbabb202eb1dde88b54f0a7677fa3
2. Position for  Custom reporter condition  0x12ca05ca3bc2f8a0bbe3c4a876294db533c54670f313e8a563167ad3a46c0ad0

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr695--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr695--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr695--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr695--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gabitoesmiapodo** [comment]
@elena-zh 

This is the best I could do:

I think ALL the information should be preloaded before showing a section, but that's not the case here, there are individual parts loaded after the section, which results in loading text flashing, spinners flashing, etc.

At this point I believe it would be a lot of work to change that, so I won't ask anyone to fix it.

Related to that, there's a problem with the "Loading Question / Market" item: it shows briefly, then it shows the question / omen market if there's something to show, or it disappears if there's nothing. So I decided to show "Question: Information not available" for the later case to avoid this issue.

These are the different variants I got to check (I may have missed some, I don't know):

- Omen Condition, question text is not available (I don't know the reasons, there's just no text): https://pr695--conditionaltokensexplorer.review.gnosisdev.com/#/conditions/0x065ebfcb8cd3e32033cfd42643578fb66a3bd6c664823b88fcf9d1c2dfb4c137
- Omen Condition, no Omen markets (question text is shown): https://pr695--conditionaltokensexplorer.review.gnosisdev.com/#/conditions/0x00af9b2462e40e7d04678054e1f734dbd1f2c0ceb6af6a79ea3cba7fa3ac9ae7
- Omen Condition, one Omen market: https://pr695--conditionaltokensexplorer.review.gnosisdev.com/#/conditions/0x5b9e7121188e8f4ee15964105ea5c002e40317fee73ff585318cd10637bcb54d
- Omen Condition, multiple Omen markets (I can only see this if my wallet is not connected, don't ask me why...): https://pr695--conditionaltokensexplorer.review.gnosisdev.com/#/conditions/0x339fd1fd3cf16bef21d548437747371ed9dd94a127e89160bec2129c29466731
- Custom Reporter with Omen market: https://pr695--conditionaltokensexplorer.review.gnosisdev.com/#/conditions/0xb3e84dbd55f0846de0a37b5a1010f5ad10d78f6d60b07519da6377ef939290fc
- Custom Reporter, no Omen market (question text is shown): https://pr695--conditionaltokensexplorer.review.gnosisdev.com/#/conditions/0x4621c84fb3bd26b461a77b1201ff0d009e3dbabb202eb1dde88b54f0a7677fa3
- Position for Omen Condition, no Omen market: https://pr695--conditionaltokensexplorer.review.gnosisdev.com/#/positions/0x737cc723f157ca3555ce554f3ceb8f4a415e3a91b30336f3a780378052e440b6
- Position for Omen condition, one Omen market: https://pr695--conditionaltokensexplorer.review.gnosisdev.com/#/positions/0x906983556f829dafd2d82800abd2e050d3bffabec1c51ed837ae3a9ce9959511
- Position for Omen condition, multiple Omen markets: https://pr695--conditionaltokensexplorer.review.gnosisdev.com/#/positions/0x4a09308ddd755ea89eac244f46f013dbfb9826d7ca557378046e6685fa8ded13
- Position for Custom reporter condition https://pr695--conditionaltokensexplorer.review.gnosisdev.com/#/positions/0x12ca05ca3bc2f8a0bbe3c4a876294db533c54670f313e8a563167ad3a46c0ad0

Regarding https://github.com/gnosis/conditional-tokens-explorer/issues/622#issuecomment-735705964

It seems there's nothing to show (question or Omen markets, I checked the code and it seems nothing's being fetched) for https://pr695--conditionaltokensexplorer.review.gnosisdev.com/#/positions/0xca80cfdee687648ceac444ab67bb8e5c9ddc43b17e136be7a73f1c688c21a704

There's nothing for the related conditions either https://pr695--conditionaltokensexplorer.review.gnosisdev.com/#/conditions/0x268328f60ffb728a769fe1699233573f35d0ab9b4406645b3f19a88808c18454 and https://pr695--conditionaltokensexplorer.review.gnosisdev.com/#/conditions/0xedd426dcca93256864b26495a325c98fdea66c9da644866512950211aa0f5119

If you are sure there should be something shown there, then ask Maxi to fix it, because the component isn't working as it should and I was implementing this under the assumption that this was properly working.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr695--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr695--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
Hi @gabitoesmiapodo , thank you for your fixes/explanation and investigation. 

So.. yes, you're right, there is a problem with the "Loading Question / Market" item. It is flashing all the time when a condition/position details are loaded. 
But.. can we fix a 'double flashing' of the section when a question/market is being loaded? (see the [video ](https://drive.google.com/file/d/1DIwQ549FLCfVaLhv0rpRr9HEvcZna0Kn/view))
Link to the condition details from the video is [here](https://conditional-tokens-explorer.dev.gnosisdev.com/#/conditions/0x00af9b2462e40e7d04678054e1f734dbd1f2c0ceb6af6a79ea3cba7fa3ac9ae7)

Still.. double margin for a custom reporter condition/position details is displayed on the place where Question / Market section should be (where it is relevant). So, when it absents, 'Loading' is flashing then disappears, double margin appears (here is the [video](https://drive.google.com/file/d/1muRWmYfEVQkloC9_EzZWDyzvJuYRfyn6/view)). 
Can we remove this double margin? 
Here are links: [ position details](https://conditional-tokens-explorer.dev.gnosisdev.com/#/positions/0x12ca05ca3bc2f8a0bbe3c4a876294db533c54670f313e8a563167ad3a46c0ad0) and [condition details](https://conditional-tokens-explorer.dev.gnosisdev.com/#/conditions/0x4621c84fb3bd26b461a77b1201ff0d009e3dbabb202eb1dde88b54f0a7677fa3).

However, that is strange as in my understanding there should not be a link to omen markets/question text when a condition type = 'custom reporter'...

Also, I cannot complete the testing of Omen conditions/positions details until issues #703 and https://github.com/protofire/omen-subgraph/pull/97 are fixed. I have added a comment there to retest the current fixes as soon as Omen bugs are fixed.

**Comment by gabitoesmiapodo** [comment]
@elena-zh 

> But.. can we fix a 'double flashing' of the section when a question/market is being loaded?

No, I can't fix it. I don't know how.

Also, I think you should stop testing everything related to this until all the issues related to the graph are fixed (#703, protofire/omen-subgraph#97 and so on). In this state, no results from my work (or yours) is reliable.

**Comment by gabitoesmiapodo** [comment]
@elena-zh 

> Now, 'Information not available' is displayed in the OMEN MARKETS section for a custom reporter conditions/positions.
However, that remains to be for me strange as in my understanding there should not be a link to omen markets/question text when a condition type = 'custom reporter'...

This is (or should be) to avoid having the `"Loading: -"` shown and then disappearing when nothing is found. Whatever the results when fetching data, something is always displayed. This way there's always something to show and no contents "jumps" happen. 

Unless somebody jumps in and is able to implement a better solution (which I'm guessing would require a lot of extra work for minimal enhancements) that's the best we can do now.

However... I can't reliably say that what's going on is what we should expect from the modifications. I changed almost nothing since your last review (that was the main change I did, the rest should be the same), but everything related to this is working really really REALLY bad right now.

**Comment by elena-zh** [comment]
Will be checked when #718 is fixed.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , I have some notes here. 
1. Omen condition without Omen markets: condition details look good. Section with Omen Markets is missing there, question section is displayed. 
But when we open the related position details, we do not see the question here, but see the Omen markets section instead. Can we replace Omen markets section with Question section for the related position details? 


2. Custom reporter condition: we are able to see the Question section there (however, we cannot add a question with text when we create a Custom reporter condition). But anyway, it might be fine as 'Information not available' is displayed there. 
But when we open the related position details, Omen markets section is displayed there. Frankly, the Omen markets section for a custom reporter position looks  bit weird.. Could it be replaced with Question section at least?



3. Omen condition and positions with Omen markets look good and consistent and do not require any changes

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr695--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gabitoesmiapodo** [comment]
@elena-zh 

Latest changes from https://github.com/gnosis/conditional-tokens-explorer/issues/718 (and `/develop` in general) weren't merged into this branch yet.

Please check if this is working now.

Anyways: if the margin's issues are fixed now, I think we could merge this PR. If other issues remain regarding the question / omen market info display we could probably ask @hpmaxi to have a look in a new issue as he worked on that component before.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , I have rechecked the issue. There is no double margins in  a condition/position details. 

Also, I have created a separate issue about the inconsistency of the info in a condition and a related position details #731 and assigned @hpmaxi on it as you have suggested above. 

Thank you!)

**Pull request merged**
