### PR TITLE
Apply CPK to all transactions in the application

### LINKED ISSUE #665: Error with the CPK
In the merge, split and report payout section
Screenshot_20201124_180848

### LINKED ISSUE #666: Check the use of the address variable in the queries
Instead, use an array with the CPK address, like this ...
```
[address, cpk.address]
```

### LINKED ISSUE #682: Filtering/searching by a current wallet does not return all the conditions created by a current wallet
Related to #547, #651

**Case 1.** 

1. Create an Omen condition
2. Create a customs reporter condition under the same wallet
3. Open filter on the Conditions list
4. Search by a current wallet

**AR:** only Custom Reporter conditions are displayed

**ER:** All the conditions, reported by the currently connected user, should be displayed (Omen and Custom reporter ones)

**Case 2.** 
While creating an Omen condition, copu your CPK address
Open Conditions list and insert the CPPK address into the search field +select option 'Creator address'

**AR:** no search results 

**ER:** all the conditions, which were created by the current CPK address, should be displayed

### LINKED ISSUE #761: Merge with section shows amounts for Metamask address (not for a CPK address)
related to #759

**Steps**: 
1. create condition with several outcomes
2. split positions
3. open merge positions page
4. select a position
5. verify positions' amounts in the merge with section

**AR**: amounts are zero as they show balances not for a CPK address, but for the Metamask address

**ER**: amounts should show an appropriate value (as for the current implementation, for the CPK address)

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #666 
Closes #665 
Closes #682 
Closes #761

### CODE REVIEW

**Comment by mariano-aguero** [comment]
List of transactions:
- Wrap outcomes
- Unwrap outcomes
- Transfer outcomes
- Prepare custom condition
- Prepare omen condition
- Allowance in the split section
- Split action
- Merge action
- Redeem position
- Report payout

**Comment by elena-zh** [comment]
Hey @mariano-aguero , really-really great job!
I have verified the changes in the PR and everything works fine. I have found only one issue: #761 , however, it does not affects on the transaction result and tokens amount calculation. 
Some issues to discuss: 
1. We indeed need to implement the changes described in #735 in order to avoid an ambiguity with an entity called 'wallet address'. I have described use-cases in the [comment](https://github.com/gnosis/conditional-tokens-explorer/issues/735#issuecomment-746733315)
2. Transactions gas fee has noticeably increased..=(
3. related to the #682 issue: conditions list does not return omen conditions when search by REPORTER / ORACLE = Current wallet. I think, it is due to the search runs based on the 'oracle' address (not based on a creator address). I guess, it is okay for the current case. I have to notice, that search by Oracle/Creator addresses returns correct values.

**Review by hpmaxi — APPROVED** [review]

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr759--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr759--conditionaltokensexplorer.review.gnosisdev.com

**Pull request merged**
