### PR TITLE
Reality.eth is not displayed in the Oracles pop-up when there are 2 oracles for a position 

### PR DESCRIPTION
**Pull request by mariano-aguero**
Feedback
Related to #633

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr685--conditionaltokensexplorer.review.gnosisdev.com

**Comment by mariano-aguero** [comment]
@elena-zh 
Could you verify that the feedback of this [comment](https://github.com/gnosis/conditional-tokens-explorer/issues/676#issuecomment-734347648) is resolved in this PR? if is OK, please approve the PR and I will merge it

Thanks

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr685--conditionaltokensexplorer.review.gnosisdev.com

**Review by elena-zh — APPROVED** [review]
LGTM!
Great job, @mariano-aguero !

**Pull request merged**
