### PR TITLE
Full fetch thegraph for positions

### LINKED ISSUE #453: Number of positions on the Conditions/Positions list got stuck on the 1000 entries
Number of positions on the Positions list got stuck on the 1000 entries, however, there is more that 1000 positions are already created. 
E.g. there is 932 positions with DAI, 103 positions with USDc and etc. (it is already > that 1000 entries)

Expected Result: show the actual quantity of position (i'm not sure about the positions. however, it would be nice to check the issue for the conditions list as well)

### LINKED ISSUE #660: It may take up to 10 sec until filter results are loaded in the select position section
1. Open Split position page
2. Select Position option
3. Open filters in the Select position section
4. filter by collateral (try several times)

**AR:** It may take up to 10 sec until filter results are loaded (see the [video](https://drive.google.com/file/d/1IuP66nHZt2kLmWcWWc7yvXRYF-8f9Zpg/view))

**ER:** show loader as soon as filter option is selected (until filter results are loaded)

### LINKED ISSUE #662: Positions list: 2nd search query does not appear when filter/search for a position
Related to #656

**Steps:** 
1. Open positions list
2. open filter's panel
3. search by collateral --> filter results appear
4. Change  a collateral in the filter

**AR:** search results for the previous option remain to be displayed. There is no another search query in the console
https://drive.google.com/file/d/1iMNqPpaxEW0bm0qeyn6Vw9evuaclo3gk/view
The same issue is reproducible when filter by creation date OR search positions using search option at the top of the page. 
https://drive.google.com/file/d/1jr3c_GbZ5vO7eSKCHpouABznNZ-QXo54/view

I have to notice, that search and filtering work fine for the conditions list (however, there are less than 1000 entries)

**ER:** search and filtering for the positions list should work as soon as a filter/search query is changed by a user

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #453 
Closes #662 
Closes #660 

This is working, has some problem with not showing the spinner immediately for some reason even when the hook returns `loading: true`. 

For conditions and users' positions, this query is not integrated because I think It won't be necessary and will cause excessive friction to test everything.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr656--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr656--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
HI @hpmaxi , 
I have reviewed the changes. Positions list shows all the available positions now. 
However, I have faced another issue: the 2nd search/filter query does not appear in the console for the positions list. As a result, previously filtered positions are displayed in the list/OR loader is displayed for an eternity on the screen. I have created a separate issue for this case #662.
Could you please take a look at it?

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr656--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr656--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr656--conditionaltokensexplorer.review.gnosisdev.com

**Review by mariano-aguero — APPROVED** [review]
Great job!

**Comment by elena-zh** [comment]
HI @hpmaxi , I have verified the changes. Works great!
However, now it would be nice to implement the ability to show more than 100 lines in the Conditions list. 
I have created a separate enhancement for it #690

**Pull request merged**
