### PR TITLE
Allow to search partially

### LINKED ISSUE #447: [FE] Condition List Search Items, improvements for searching in the subgraph
We need some fields to be of type string to be able to use the suffix _contains and improve the search in thegraph

Fields:
- conditionId
- questionId
- oracle
- creator

### LINKED ISSUE #507: [FE] Position List Search Items, improvements for searching in the subgraph
We need some fields to be of type string to be able to use the suffix _contains and improve the search in thegraph

Fields:

- positionId
- collateralToken (address)
- wrappedToken (address)
- conditionIds

Related issue https://github.com/gnosis/hg-subgraph/issues/23

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #507 
Closes #447

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr508--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — CHANGES_REQUESTED** [review]
Conditions list's partial search works great.

On the other hand, I couldn't test the positions list's partial search, it crashes when I select an option from the dropdown (any option).

Oct-23-2020 11-27-09

**Comment by mariano-aguero** [comment]
> Conditions list's partial search works great.
> 
> On the other hand, I couldn't test the positions list's partial search, it crashes when I select an option from the dropdown (any option).
> 
> Oct-23-2020 11-27-09


It's quite a strange problem, since it hasn't happened to me, anyway there is an issue to work it    https://github.com/gnosis/conditional-tokens-explorer/issues/506

**Review by hpmaxi — APPROVED** [review]

**Comment by elena-zh** [comment]
Hi @mariano-aguero , I have reviewed the changes as well. 
Works great, however, there are few issues from my side: 
1. Partial search by collateral symbol on the positions list returns all the positions (as well as the search by collateral symbol with no match)
partial search symbol

2. It is more question than an issue: when I search by a wrapped collateral address as a not logged in user (or a user who has no any positions with amounts), I get a list of positions.. when I open a position details, I do not see any info about a wrapped collateral address and etc. (see the video - https://drive.google.com/file/d/1kguvecO9wPrLw36HKJ1KVau8TB4MzOXp/view ). Is it an expected behavior? Or we should not show such a positions to a user who is not positions' owner?

**Comment by mariano-aguero** [comment]
> Hi @mariano-aguero , I have reviewed the changes as well.
> Works great, however, there are few issues from my side:
> 
> 1. Partial search by collateral symbol on the positions list returns all the positions (as well as the search by collateral symbol with no match)
>    partial search symbol

Fixed

> 2. It is more question than an issue: when I search by a wrapped collateral address as a not logged in user (or a user who has no any positions with amounts), I get a list of positions.. when I open a position details, I do not see any info about a wrapped collateral address and etc. (see the video - https://drive.google.com/file/d/1kguvecO9wPrLw36HKJ1KVau8TB4MzOXp/view ). Is it an expected behavior? Or we should not show such a positions to a user who is not positions' owner?

I think is an expected behaviour, because a wrapped collateral address can exist, so you can search for a contract address. The existence of this contract means that exist some wrapped tokens in that position

**Comment by mariano-aguero** [comment]
> Conditions list's partial search works great.
> 
> On the other hand, I couldn't test the positions list's partial search, it crashes when I select an option from the dropdown (any option).
> 
> Oct-23-2020 11-27-09

I fix this bug on this PR

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr508--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — APPROVED** [review]

**Comment by elena-zh** [comment]
Verified. Works great!
Some notes: 
1. it would be nice to allow a partial search by a collateral on the positions list - #524 
2. Search by a conditionID returns results when fill in the search field with a space - #528

**Pull request merged**
