### PR TITLE
[DEV] Positions list is not loaded to a not connected user

### LINKED ISSUE #809: [DEV] Positions list is not loaded to a not connected user
Reproducible in **DEV** environment only. 

1. open the app as a not connected user
2. go to the positions list
3. open Report payouts page (or conditions lost and filter it by 'REPORTER / ORACLE = current wallet')

**AR**: 
p.2 the positions list is eternally being loaded
p.3 conditions section shows an error n the Report Payouts page

image

**ER**: positions list is opened, conditions section shows 'User is not connected to wallet.'

**Note**: the same behavior is applicable for positions section on the rest app pages.

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #809

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr810--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr810--conditionaltokensexplorer.review.gnosisdev.com

**Review by elena-zh — COMMENTED** [review]
Positions section looks good to me. 

Conditions section now shows all the opened conditions, however, the message  'User is not connected to wallet.' should be shown to a not connected user on the Report Payouts page and in the Conditions list when it is filtered by  'REPORTER / ORACLE = current wallet'. 
no conditions

@mariano-aguero . could you please fix it?

**Comment by mariano-aguero** [comment]
> Positions section looks good to me.
> 
> Conditions section now shows all the opened conditions, however, the message 'User is not connected to wallet.' should be shown to a not connected user on the Report Payouts page and in the Conditions list when it is filtered by 'REPORTER / ORACLE = current wallet'.
> no conditions
> 
> @mariano-aguero . could you please fix it?

Fixed

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr810--conditionaltokensexplorer.review.gnosisdev.com

**Review by elena-zh — APPROVED** [review]
LGTM!

**Pull request merged**
