### PR TITLE
[FE / UI] Add Split Position Result Modal / Info

### LINKED ISSUE #243: [FE / UI] Add Split Position Result Modal / Info
We need to do something after splitting a position.

Adding a modal with a list of the split positions should be enough, but we can't just do nothing.

**Maybe this would do it:**

- Title: "Split Positions"
- Table with the usual table columns for "Select Position."
- It should be possible to click each row to navigate to each position's details page. Also to copy the position's ID, etc.
- An "OK" button.

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #243 

If we split a condition into some positions, we can see at the end the new modal with all the information required

Peek 15-09-2020 13-09

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr251--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr251--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gabitoesmiapodo** [comment]
@mariano-aguero 

- It's OK if you want to add the "amount" column and it's no too troublesome, but I don't think it's necessary. Feel free to ignore it.
- We should add the close button as in the other modals. And now that I can see it, the "OK" button looks a little out of place, so we should remove it.
- The "OK" / "Checkmark" icon looks a little weird there, we should remove it and add some kind of explanatory text. Maybe something like "Positions were successfully split from `condition ID`." I think you can use the `subTitle` prop for that.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr251--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr251--conditionaltokensexplorer.review.gnosisdev.com

**Comment by mariano-aguero** [comment]
> @mariano-aguero
> 
> * It's OK if you want to add the "amount" column and it's no too troublesome, but I don't think it's necessary. Feel free to ignore it.
> * We should add the close button as in the other modals. And now that I can see it, the "OK" button looks a little out of place, so we should remove it.
> * The "OK" / "Checkmark" icon looks a little weird there, we should remove it and add some kind of explanatory text. Maybe something like "Positions were successfully split from `condition ID`." I think you can use the `subTitle` prop for that.

Done

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr251--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gabitoesmiapodo** [comment]
This is OK.

Added the "Open in new window" link, it should look like this:

Screen Shot 2020-09-16 at 17 05 45

**Review by gabitoesmiapodo — APPROVED** [review]

**Comment by elena-zh** [comment]
Verified. Looks good to me. 
However, I have created 2 connected issues:
1.Split Position Result Modal window appears when transaction is failed #276

2. Split Position Result Modal window  UI bugs #277

**Pull request merged**
