### PR TITLE
UI - '...date is invalid' appears as soon as start typing into a date filter

### LINKED ISSUE #661: UI - '...date is invalid' appears as soon as start typing into a date filter
Related to #625

1. Open Conditions list
2. Open filter's bar
3. Start typing into the date filter

**AR:** '...date is invalid' appears as soon as start typing into a date filter

**ER:** add a delay in 1 sec after a user stops typing into the field, then show a message if a date is invalid

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #661 

Added a debounce of 3 seconds, 1 seemed little

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr698--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — APPROVED** [review]

**Comment by elena-zh** [comment]
@gabitoesmiapodo,  the issue is verified and works fine.
However, a delay of 3 seconds is added to the 'Clear' button's behavior as well. So now it is impossible to clear out the field when it is filled with incorrect value. I have created a separate bug for this case #706

**Comment by gabitoesmiapodo** [comment]
@elena-zh 

It was @mariano-aguero who fixed this, so the message should be addressed to him, I think.

Anyways, I still think the delay is unnecessary.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , sorry about that

**Pull request merged**
