### PR TITLE
Fix web3 modal

### PR DESCRIPTION
**Pull request by mariano-aguero**
Mmm something is breaking the web3modal styles at the build time. I think is the datatables, but I'm not 100% sure. The best solution I found was to set the correct styles in the web3Modal styles.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr151--conditionaltokensexplorer.review.gnosisdev.com

**Comment by mariano-aguero** [comment]
Preview ....
Screenshot_20200828_165302

**Comment by lmcorbalan** [comment]
:comet:

**Comment by gabitoesmiapodo** [comment]
Changed to draft. Don't merge this.

**Comment by gabitoesmiapodo** [comment]
This is a really weird issue.

It seems that for some reason CSS is leaking from some components to `web3modal`. Those components are `Footer` and `Header`

What @mariano-aguero did is fine, it fixes the problem, but it's kinda hacky and not future proof (any modification to `Footer` / `Header` / `web3Modal` will possibly break it). I couldn't for my life find why this is happening, I tried moving the components around, changing their names, etc., but code keeps leaking.

I opted for a compromise: I added a class to the components, and a `&.theClassName` to the styled components' code so the CSS attributes will be only applied to the correct components.

It seems it works fine now, `web3Modal` is not affected anymore, and neither are `Footer` or `Header`.

Also - for some reason- you won't see this problem on the development environment, you need to build this to see it. Travis automatic deployment should be enough to test it, though.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr151--conditionaltokensexplorer.review.gnosisdev.com

**Pull request merged**
