### PR TITLE
Use collateral with error and loading

### LINKED ISSUE #172: [FE] Add custom token: fetching spinner / show errors
This modal is not showing a spinner when retrieving data, nor it's showing errors when something happens.

That should be fixed.

See #171

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #172 

This change `useCollateral` hook to return error and loading state. When you add a custom token in split position page we should see a spinner or an error. Errors have the original message, maybe this could be improved mapping common errors to a string.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr202--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr202--conditionaltokensexplorer.review.gnosisdev.com

**Review by mariano-aguero — APPROVED** [review]
LGTM

**Review by gabitoesmiapodo — APPROVED** [review]
Seems to work fine.

**Comment by elena-zh** [comment]
Two UI issues with validation messages are found under this task. 
Reported in #223

**Pull request merged**
