### PR TITLE
(Fix) Sometimes validation message does not appear 

### LINKED ISSUE #495: Prepare condition: restrict a year input up to 4 numbers in date field on the Prepare Omen condition page
Related to #434, #491 
See the pic 

It would be nice to limit a year input to 4 digits

### LINKED ISSUE #591: Date: sometimes validation message does not appear when a date field is filled in with incorrect value
Related to #491

See the pics: 
: 

There is no validation message that the date is out of range and that the To is grater that From (for filters) when manually type 02/31/2222 value into the field 

**Expected Result:** validation messages should appear

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #591
Closes #495

I've changed a few things here, but the solution is still not perfect, and I think there could be a few extra issues which I might have not noticed:

- **Filters:** we don't show an error anymore when from / to are out of range. If that's the case, `from` is forced to the minimum date, and `to` is forced to the maximum date. No need to tell anything to the user, as is the case with the `min / max` filter.
- **Prepare Omen Condition:** I changed the error for out of range dates, instead of something like "Date must be between 01/01/2000 and 01/01/2100", now it shows the month name to avoid confusion between `mm/dd/yyyy` and `dd/mm/yyyy` users.
- **Date validity:** I think it's impossible to enter an invalid date using the calendar, but when using the keyboard anything goes. The date input makes it really tricky to detect if the entered date is valid or not, because we can only get an empty string for an invalid date, or the full string for a valid date. So, I can't determine if the user is just in the middle of writing `12/12/yyyy`, or if they wrote `31/02/2020`. Technically both are invalid, but I'd wish to show an error only for the later case... which I don't think I could do without complicating things a lot (maybe there's a way I don't know of).
The result of this is that if the user enters the date field using the keyboard, the script sees an empty value / invalid date, and an error is triggered. We could simply show nothing and let the user find the error, though... As long as the form can't be sent, I'm OK with it.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr625--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr625--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr625--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr625--conditionaltokensexplorer.review.gnosisdev.com

**Review by hpmaxi — APPROVED** [review]

**Comment by elena-zh** [comment]
Hi @gabitoesmiapodo , I have verified the changes and they LGTM. 
The only thing I would like to discuss is a hint for dates range displaying. Now it appears when search results/no search results for an out-of-range date are displayed in the grid. 
May be.. we should show this hint on a regular basis when hover a mouse on the calendar icon, what do you think?


As for the case with manual input for date fields, I have created a separate task #661, where I proposed to add a delay in 1 sec after a user stops typing into the field, and then show a validation message is a date is not valid.

**Pull request merged**
