### PR TITLE
(Feature) Open links in new window

### LINKED ISSUE #275: [FE] Nothing happens when clicking on a collateral on the Positions list
Related to the #248, #256

Open positions grid and click on the collateral: nothing happens

**Expected Result:** position details page should be opened.

### LINKED ISSUE #334: [UI/UX] Open links in new window on middle click
This is just a personal preference of mine, but I use to open lots of tabs / windows using middle click, and some of the links here don't work that way, specially links for conditions / positions on tables.

Maybe the same for dropdown menus, and table rows?

Main menu and footer's links are fine, BTW.

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #334
Closes #275 

OK, this is a slightly complex one:

- All items that should be a link (that is: items that take the user to a different section) are a links now. That includes position ids, condition ids, dropdown items, etc.
- Items in dropdowns that don't take the user to a different section are, well... items that do something when clicked on (ie: transfer outcomes) as they always have been.

**Regarding the mouse buttons' behaviour:**

- Left click on link: go to section.
- Left click on action (ie: wrap collateral): display modal, or whatever it should do.
- Middle click on link: open new tab, go to section.
- Middle click on action: do nothing (this is the same behaviour as on the Instagram, Twitter, and Facebook web apps).
- Right click on link: the usual context menu (open in new tab, etc.)
- Right click in action: the usual context menu (copy text, etc.).

**There's a small catch though:**

Dropdown items like "Redeem", "Split Positions", "Merge Positions", etc. are links but at the same should auto complete some fields in the target form. This works well with regular left clicks (open link in the same window), but it doesn't work so well when using middle click to open multiple tabs.

For example:

- Go to any condition's details page.
- Open the top right dropdown.
- Always using middle click open "Split Position", "Merge Positions", and "Report Payouts".
- Check the opened tabs, and you'll see that only one (or maybe none) of the tabs has the pre-filled fields correctly pre-filled. 

This is because there's a unique identifier for the storage item used to transfer data, and that storage item is deleted when the section loads, making it unavailable for the other tabs.

There's an issue for that here:  #378

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr377--conditionaltokensexplorer.review.gnosisdev.com

**Review by hpmaxi — APPROVED** [review]
There are some conflicts pending of resolution.

We have to think a good way to handle our solution for passing ids to local storage in a robust way to avoid replacing ids between calls.

**Review by mariano-aguero — APPROVED** [review]

**Comment by mariano-aguero** [comment]
@gabitoesmiapodo solve conflicts and feel free to merge

**Comment by elena-zh** [comment]
@gabitoesmiapodo , I have verified the changes. 
Frankly, only a few links work as it is described above on my PC (or browser, or with my mouse). These are links are at the top of the app and footer links


As for the rest links.. Let me describe: 
1. Grid links and grid lines on the Positions/Conditions pages
 - Middle click starts a 'scroll' mode 
 - Right click does not open a usual context menu (open in new tab, etc.)



2. Action buttons as links in grids:
 - Middle click starts a 'scroll' mode 
 - Right click does not open a usual context menu (open in new tab, etc.)


3. Action buttons as links in a condition/position details pages:
 - Middle click does nothing
 - Right click does not open a usual context menu (open in new tab, etc.)



Additionally, I changed my PC setting to use a middle touchpad button as a middle click, but it did not help me to get the expected behavior for links clicks in the app..

**Comment by gabitoesmiapodo** [comment]
@elena-zh just checked https://conditional-tokens-explorer.dev.gnosisdev.com/#/positions and https://pr377--conditionaltokensexplorer.review.gnosisdev.com/ (this PR's build) and I don't have any of those issues.

Could it be a computer / mouse configuration issue? Or maybe some browser cache issue, or even a temporary deploy / build issue.

This is what I'm getting on https://conditional-tokens-explorer.dev.gnosisdev.com/

Middle click:

Sep-29-2020 15-36-59

Right Click:

Screen Shot 2020-09-29 at 15 38 36

Middle click on list dropdown:

Sep-29-2020 15-39-56

Right click on list dropdown:

Screen Shot 2020-09-29 at 15 41 35

Middle click on details dropdown:

Sep-29-2020 15-43-14

Right click on details dropdown:

Screen Shot 2020-09-29 at 15 44 04

**Comment by elena-zh** [comment]
@gabitoesmiapodo, 
Who knows, it might be a build issue.. 
Anyway, I have rechecked the issue today. Everything works as expected for me now. 
Thank you, I'm closing the task.

**Pull request merged**
