### PR TITLE
Report payouts

### LINKED ISSUE #20: Report payouts
- Manually enter raw conditionId
- Populate outcome slot
- Enter payouts
- Validate payouts (positive, at least one non 0)
- Validate oracle
- Submit

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #20 

Workflow to report a payout
- [x] Manually enter raw conditionId
- [x] Populate outcome slot
- [x] Enter payouts
- [x] Validate payouts (positive, at least one non 0)
- [x] Validate oracle
- [x] Submit

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr43--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr43--conditionaltokensexplorer.review.gnosisdev.com

**Comment by mariano-aguero** [comment]
How you can test it:
- Create a condition in the home section
- Go to the report payout section, and submit a payout
- Try to report the same condition, must throw an exception with a validation string

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr43--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr43--conditionaltokensexplorer.review.gnosisdev.com

**Comment by mariano-aguero** [comment]
Query to use to check the payouts array

```
{
  conditions(where : { id:"0x40bbd07844c61f7c5406b934bfa1d4669315c83260617e989c3438e8bcd40025"}) {
    id
    oracle
    questionId
    outcomeSlotCount
    payouts
    positions {
      id
      indexSets
      activeValue
      collateralToken {
        id
        activeAmount
      }
      conditions {
        id
        resolved
        resolveTimestamp
      }
    }
  }
}

```

Screenshot_20200803_100138
Screenshot_20200803_100316

**Comment by mariano-aguero** [comment]
Branch updated with all the changes from develop

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr43--conditionaltokensexplorer.review.gnosisdev.com

**Comment by mariano-aguero** [comment]
Something to take into account, you can report a condition without having been splitted

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr43--conditionaltokensexplorer.review.gnosisdev.com

**Pull request merged**
