### PR TITLE
Bump release `v0.3.0`

### PR DESCRIPTION
**Pull request by davidalbela**
Version 0.3.0 (2020-12-03)
====================

- Fix regression in redeem #734
- Question/Outcomes/Category is not displayed in an Omen condition details when create in it the CTE #718
- Do not apply 3 sec of a delay when a date field is filled in with a correct value #711
- Enable 'Clear' button as soon as a value appears in the Date filter #706
- Split position: The app is crashed when switch to the Position option #705
- T[here is no link to Omen markets when create an Omen condition #703
- Lists filter results are not reset after connecting to a wallet  #702
- [UX / UI] Remove unnecessary "Close button" #696
- Redeem is not working (positions are not zero out and no tokens are returned to a wallet) #693
- Cannot resolve an Omen condition which was created by a currently connected wallet #692
- Full fetch thegraph for conditions #690
- Typos in the Terms/Cookie policy pages  #687
- Container is too big when there is no positions for a condition on a condition details page #674
- Condition Id field is cleared out when select a position to merge with for a position with 2 conditions #673
- UI issues with Cookie/Privacy Policy pages #672
- UI issues with Terms and Conditions page #671
- Positions list: 2nd search query does not appear when filter/search for a position  #662
- UI - '...date is invalid' appears as soon as start typing into a date filter #661
- It may take up to 10 sec until filter results are loaded in the select position section#660
- [Staging+Prod] cDAI icon is blinking when open Collateral filter in the Postitions list #577
- [FE] Add spinner to Outcomes table in "Report Payouts" #596
- Filter by collateral: loader is not always displayed when switch between collaterals in the filter #604
- Rounding issue in the merge positions preview #613
- Report payouts: not to show 'At least one payout must be positive' warning until clear out all the payouts fields #615
- No question text for an Omen condition when there is no relevant Omen markets #622
- UI - wrap text by words in the outcomes section on a position details page #626
- Conditions filters: 'Go' arrow is enabled when empty value is displayed in the 'Number of Outcomes' fields #630
- Reality.eth is not displayed in the Oracles pop-up when there are 2 oracles for a position #633
- Empty The reported array is displayed after successful report payouts #642
- UI: selected position/condition is not highlighted in the select position/condition sections  #649
- Report button should be enabled and call connection pop-up on the Report payouts page #652
- 'Use Position Balance ($0.00)' should be disabled when no positions to merge are selected #653
- 'Use Wallet Balance' remains to display wallet amount of DAI when switch to 'Position' option #654
- 'Merge with' section shows positions with 0 balance to merge  #657
- Previously selected option in filter dropdowns remain to be highlighted after Clear Filters #659

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr738--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — APPROVED** [review]

**Comment by davidalbela** [comment]
Add #734 PR to the release

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr738--conditionaltokensexplorer.review.gnosisdev.com

**Review by elena-zh — APPROVED** [review]
LGTM!

**Pull request merged**
