### PR TITLE
Positions list in condition detail

### LINKED ISSUE #328: [FE] After split/merge the split positions page is not updated
After a new position is created it should be visible for selection in select positions modals. This works with a refresh.

### LINKED ISSUE #347: [FE] Add positions' list to Condition Details
We should add a list of the condition's split positions to the Condition Details section. This could make some things easier for the user.

**Design:** https://zpl.io/bAMGOJq (this is a full "Omen Condition" design, so take into account that some info may or may not be available).

### LINKED ISSUE #365: [FE] Balance of a position is not cleared out after a merge
Here is the description: 
**Condition:** 0xa21d0f0f0cfb53b3ca9a70fdae20be0888c9c6058a93df050e483d08d181904a
	1 position 0x0f601160e4bc2506b847a4eceab8931ddfdb1a36a24ca91f4fd7b4f4a649d6aa with 1 balance
	2 position 0x57410364a7b9ac15b6b980492b4e1aa761923dd3fbd156eb1e4a3643841db29f with 1 balance
	3 position 0xb5b259c452a194ecad208d49c05994d4c5b0f915b5f7cf63f7d5f6ac71a92019	with 1 balance, but after position split it has  0 balance
	
**the 3rd position**  is splitted to: 
	3.1 - 0xffbb5a10865dc9d374e75216199d5290cb81beb39b6fdc7516e2e809c4b71f37 - 1  -merged 
	3.2. -  0x0b2217c5a22f563d63bd4d15ac916b703e8dda2f93289e16c805c90fd4a242dd - 1 - merged
	3.3. -  0xe4ff4f272dde48ca025e085b761c4d75831d3be92fb8b468ce863cabf0653f03 - 0 (has 0 balance after split? #289)
	
**Positions 3.1 and 3.2. were merged** into the 0x0bbd02179644019371e8a5afc6ff5be333e466285a1b52f7322bd6a81ef0db70 . It has 1 balance
	
However, **positions 3.1 and 3.2.** still have the balance =1. 

**Expected result:** positions 3.1 and 3.2. should have the balance =0,00 after a merge?

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #347 
Closes #365 
Closes #328

I also tested #365, #328 that why I'm closing them here.

This looks like this.
Captura de pantalla de 2020-10-07 16-47-09
Captura de pantalla de 2020-10-07 16-47-26

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr441--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr441--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — APPROVED** [review]
Looks good, I modified a few things.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr441--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
#347 and #365 look good to me
#328 is reopened (comment is in the ticket)

**Pull request merged**
