### PR TITLE
(Feature) Disable dropdown menu items

### LINKED ISSUE #316: [UX/UI] Positions list/details: Disable 'Redeem' / 'Split' action button when ERC1155 balance is 0.00
- Disable the 'Redeem' action button when ERC1155 balance is 0.00 for a position on the Positions list / Position details pages
- Disable the 'Redeem' button for a not logged in user. 
- Also, it would be nice to disable the 'Split' button from a Position details page when ERC1155 balance is 0.00 for a position, and when a user is not logged in.

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #316

It think I got all the combinations, but I may have missed some.

In short: when the user can't do something, the items are disabled, not hidden.

Screen Shot 2020-10-13 at 16 23 13
Screen Shot 2020-10-13 at 16 24 33
Screen Shot 2020-10-13 at 16 24 44
Screen Shot 2020-10-13 at 16 25 00

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr461--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr461--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr461--conditionaltokensexplorer.review.gnosisdev.com

**Review by hpmaxi — APPROVED** [review]

**Comment by elena-zh** [comment]
Verified. 
Only one option remains to be hidden - Report payout for a Resolved condition. 
I have added a comment to disable it (not to hide) in #458

**Pull request merged**
