### PR TITLE
(Feature) CPK Address switching

### LINKED ISSUE #735: Allow user to switch between authenticated address and CPK addresses
To avoid confusing and complicated UX of dealing with EOA/authenticated address and CPK addresses in one view, we decided on the dev sync today that we should allow users to switch between their EOA/authenticated address and any CPK addresses associated with that account.

Users should be able to switch easily between viewing the interface as the EOA/authenticated address and the associated CPK addresses. One option would be with radio buttons in the dropdown.

image

CPK would be selected by default, so that it is maximally compatible with Omen.

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #735

I'm creating this as a draft so @mariano-aguero can jump in later and finish it.

This is what we got so far:

Screen Shot 2020-12-23 at 15 46 03
Screen Shot 2020-12-23 at 15 46 09

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr782--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr782--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr782--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr782--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr782--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
Hi @mariano-aguero !
I know that the PR it in the draft now, but anyway, this feature exists now: each time when I switch on/off Use my CPK address option, the connection window is closed, and this looks not user-friendly a bit.
https://drive.google.com/file/d/1x-cJwXpREaKxE5P8vY2ixx98nCDbHq1A/view
Can we leave the connection opened? I see, that when Use CPK address option is selected, an additional row with a CPK address appears there. So, by the switching off the option we can simply gray out and disable this row instead if hiding the window..
What do you think?

**Comment by mariano-aguero** [comment]
> Hi @mariano-aguero !
> I know that the PR it in the draft now, but anyway, this feature exists now: each time when I switch on/off Use my CPK address option, the connection window is closed, and this looks not user-friendly a bit.
> https://drive.google.com/file/d/1x-cJwXpREaKxE5P8vY2ixx98nCDbHq1A/view
> Can we leave the connection opened? I see, that when Use CPK address option is selected, an additional row with a CPK address appears there. So, by the switching off the option we can simply gray out and disable this row instead if hiding the window..
> What do you think?

Yes, sure, I will change it and leave the dropdown opened

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr782--conditionaltokensexplorer.review.gnosisdev.com

**Review by hpmaxi — APPROVED** [review]

**Comment by elena-zh** [comment]
Verified. 
Works fine except several issues: 
#797 - Update app pages when switch on/off 'Use CPK Address' option
#798 - Impossible to merge positions when 'Use CPK Address' option is switched off
#799 - No tokens are returned to wallet when merge all positions with 'Use CPK Address' option switched on
#800 - No tokens are returned to wallet when redeem positions with 'Use CPK Address' option switched on

**Pull request merged**
