### PR TITLE
Integrate the CPK and detect any existing proxies

### LINKED ISSUE #547: Integrate the CPK and detect any existing proxies
We should implement the CPK so that users can frictionlessly interact with their conditional tokens from Omen and also so the conditional tokens explorer can be used as a safe app.

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #547

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr651--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr651--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr651--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr651--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr651--conditionaltokensexplorer.review.gnosisdev.com

**Comment by mariano-aguero** [comment]
I'm facing a problem with the following transactions:
- Split, Merge and report payouts

Screenshot_20201124_180848

Is the same error for all the transactions, I will not waste more time with this issue, we can create another issue to check this error, for the moment I think is not necessary to implement the CPK in this sections, the most important (prepare condition) works

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr651--conditionaltokensexplorer.review.gnosisdev.com

**Review by hpmaxi — APPROVED** [review]

**Comment by elena-zh** [comment]
Verified. 
Several issues are found and need to be fixed: 
#693 Redeem is not working (positions are not zero out and no tokens are returned to a wallet)
#682 Filtering/searching by a current wallet does not return all the conditions created by a current wallet
#692 Cannot resolve an Omen condition which was created by a currently connected wallet

**Comment by elena-zh** [comment]
Verified. 
Notes are [here](https://github.com/gnosis/conditional-tokens-explorer/pull/651#issuecomment-734914448)

**Pull request merged**
