### PR TITLE
Add 'Loading...' until a wrapped collateral address is loaded

### LINKED ISSUE #771: Add 'Loading...' until a wrapped collateral address is loaded
1. Open a Positions details page with a positive balance of ERC1155 token
2. Wrap to ERC 20 
3. Verify the wrapped collateral address section

**AR**: '0x' is displayed there (until reload the page)

**ER**: show 'Loading...' until a wrapped collateral address is loaded

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #771 

I think is not necessary to add a loading, the problem is other thing, the wrapped collateral address wasn't being updated correctly

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr778--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
Hi @mariano-aguero , however, the issue is still there.. 
I see 0x each time when I wrap a collateral for the 1st time

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr778--conditionaltokensexplorer.review.gnosisdev.com

**Comment by mariano-aguero** [comment]
@elena-zh can you verify again ?

**Comment by elena-zh** [comment]
@mariano-aguero , now it is ok. 
Thanks!

**Review by hpmaxi — APPROVED** [review]

**Pull request merged**
