### PR TITLE
(Feature) Better typography for addresses

### LINKED ISSUE #177: [UI/UX] Better typography for addresses
Find and use a better monospaced typography for numbers / amounts / addresses.

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #177

It should look better now.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr203--conditionaltokensexplorer.review.gnosisdev.com

**Review by hpmaxi — APPROVED** [review]

**Review by mariano-aguero — APPROVED** [review]

**Comment by gabitoesmiapodo** [comment]
As per @elena-zh request here there are a few before / after screenshots:

It used to look like this ('monospace' font):

Screen Shot 2020-09-09 at 16 08 36

And addresses should look like this now, which I think is more in line with the rest of the typography, but at the same time it's using a monospaced font so addresses are aligned ('Roboto Mono' font):

Screen Shot 2020-09-09 at 16 08 47

**Comment by elena-zh** [comment]
@gabitoesmiapodo , thank you for the explanation. 
So, currently I have some doubts about the current design. As per the stylequide, we should not have any other fonts but Averta, but 'Roboto Mono' font is applied onto the grid lines fonts.  
Also, the grid lines title has font-size =14px, while grid lines have  font-size =15px
guide

now

What do you think if we apply  font-family "Averta, monospace" to the grid lines and make font-size to be equal to the grid headers' one (14px)?
averta+14

Thanks

**Comment by gabitoesmiapodo** [comment]
@elena-zh These guidelines are flexible, so there's room to make some changes of our own (unless the customer / company's designer specifically asks us not to do so, of course).

In this case I need for the addresses to align vertically, and there's no way to do that with Averta or any of the suggested typographies IIRC, so I'm using an alternative only for these particular items. Plain default `monospace` typography looks ugly, so I'm using this "Roboto Mono" font, which looks _more or less_ the same than Averta (that is, unless the user is really nit-picky). Averta is used for every other text / numbers.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , got it. Thanks for the explanation!

**Pull request merged**
