### PR TITLE
(Feature) Select condition / position for redeem position and split position

### LINKED ISSUE #513: [UI/UX] Redeem Positions: Select Positions
Design: https://zpl.io/VYed9Wn

### LINKED ISSUE #515: [UI/UX] Split Position: Select Condition / Select Position
Design: https://zpl.io/adgm8zL

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #513
Closes #515 

Depends on #571 
Depends on #582  

Only added the half finished components to the sections, this still needs a lot of work.

**Notes:** 

- For redeem positions, check the relevant points from (ignore any that might be outdated for this new workflow) https://github.com/gnosis/conditional-tokens-explorer/issues/546
- For split position, check if this is still valid https://github.com/gnosis/conditional-tokens-explorer/issues/542

Screen Shot 2020-11-03 at 16 00 42
Screen Shot 2020-11-03 at 16 00 53
Screen Shot 2020-11-03 at 16 02 08

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr583--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr583--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
Hi @mariano-aguero !

I have verified the changes. Great Job!! However, there are some issues to fix: 
1. #629 - The edited partitioning of outcomes is not saved on the split positions page
2. #631 'Use Wallet Balance' shows incorrect value when split a position on the split positions page
3. #634 - Positions with 0 balance are displayed in the list when split a position
4. #635 - The app is crashed when select a position to split as a not logged in user 
5. #637 - Position id is not pre-selected when navigate to the Split position page from Positions list/Position details page
6. #640 - Position id is not pre-selected when navigate to the Redeem position page from Positions list/Position details page
7. #641 - No redeemable positions when 1 of the conditions is resolved for a position with >=2 conditions
8. #643 - Cannot return a certain amount of a collateral when position has >= 2 conditions

Thank you!

**Comment by mariano-aguero** [comment]
Closes #629
Closes #634
Closes #635
Closes #637
Closes #640

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr583--conditionaltokensexplorer.review.gnosisdev.com

**Review by mariano-aguero — APPROVED** [review]

**Comment by elena-zh** [comment]
Verified and LGTM. There are some related issues are left to resolve for:
**Redeem position page:**  
1. issue with 'special' positions is still there - #485
2. impossible to redeem several position when 1 of the conditions is resolved for a position with >=2 condition - #641
3. Cannot return a certain amount of a collateral when position has >= 2 conditions - #643
4. Low priority enhancements - #646, #648

**Split positions page:** (low priority cases)
1. Issue with ''Use Wallet Balance' button - #654
2. Need to Disable sorting by Reporter/Oracle and QuestionID in the select condition section #647
3. UI issues with select position/condition sections: #649

**Pull request merged**
