### PR TITLE
(Feature) Connect modal styles

### LINKED ISSUE #178: [UI/UX] Connect Modal
Connect Modal needs styling.

Design: https://zpl.io/aMOdXk3

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #178 
Related to #212 

Design's here: https://zpl.io/aMOdXk3

**A few notes about this:**

- It's not currently possible to modify the layout or functionality of _web3Modal_ in any officially supported way (https://github.com/Web3Modal/web3modal/issues/44), nor it's simple to do it in any unofficially supported way...
- ... but anyways I added some CSS to make it look more like it looks in the design.
- I used the wallet icons provided by the plugin. I think that - while not exactly the same seen on the design- they're fine.
- This is mostly related to #212, but - as stated- it's not possible to add a close button to this component. Addressing the "impossible to close" issue, it should be possible to close the modal by clicking the background overlay (which may not be obvious at first). I added some _hacky_ CSS to make having a "Close" button possible (and it seems to work), but be warned that this is kind of not future proof... Any unexpected modifications to the modal window's width or height could mess up the button's location. I think this is OK for now, but have in mind that it's far from perfect and eventually it could be done better when there's support for it.
- I also added some CSS to make the _"Wallet Connect"_ modal look a bit better. This is an external module and we have not mucho control over it, but it looks somewhat better now.

**It looked like this:**

Screen Shot 2020-09-09 at 16 33 57

**And it should look like this now:**

Sep-09-2020 16-07-27

Sep-09-2020 16-07-41

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr225--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr225--conditionaltokensexplorer.review.gnosisdev.com

**Review by hpmaxi — DISMISSED** [review]
I can't see the close button for the connect modal, but it's visible if I choose wallet connect.

**Comment by gabitoesmiapodo** [comment]
@hpmaxi can you share a screenshot and specify your browser? I only tested this on Chrome.

Wallet connect's modal is a totally different one from the initial one, so it is what it is.

**Comment by hpmaxi** [comment]
> @hpmaxi can you share a screenshot and specify your browser? I only tested this on Chrome. I'll just remove the button "feature" if it ends up being too problematic.
> 
> Wallet connect's modal is a totally different component from the one you see at first, so it is what it is.

@gabitoesmiapodo 
Captura de pantalla de 2020-09-09 17-36-19

I'm using chrome too `Versión 85.0.4183.83 (Build oficial) (64 bits)`

**Comment by mariano-aguero** [comment]
Works for me
Screenshot_20200909_180132

**Review by mariano-aguero — APPROVED** [review]
LGTM

**Comment by mariano-aguero** [comment]
> LGTM

Ok I detect something weird, If you execute `yarn build`, and then execute `serve -s build` , when you access the application at ` http://localhost:5000` the cross is not displayed

Screenshot_20200909_181041

**Comment by gabitoesmiapodo** [comment]
@mariano-aguero Yeah, suspected as much... I didn't try to run the built app, but it seems I'll have to.

**Comment by elena-zh** [comment]
I have reviewed the latest changes in the pr. 
1. I still do not see the cross icon on the login modal window
no cross

2. It would be nice to reduce transparency of the white background overlay due to title of the modal windoe seems to overlap menu action buttons
wallet connect 2

3. also, there is no backdgound overlay when the WalletConnect pop-up appears in order to reconnect the app with an account:
wallet connect

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr225--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr225--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
I have rechecked the latest build. 
Looks much more better, but still walletconnect pop-up seems to overlap menu action buttons. Try this flow: 
1. Connect via wallet connect
2. Close the connection in a mobile app (I use Trust Wallet)
3. Refresh the app page --> see the results
still

**Comment by gabitoesmiapodo** [comment]
@elena-zh @mariano-aguero @hpmaxi 

- The close button should be visible on the develop and built versions now. 
- The problem that affected the button's visibility was affecting the "click the overlay to close" functionality too, so that should be fixed now.
- Got the "Wallet Connect" modal's overlay back (it's a completely different one from the base modal's overlay...), so the white background should be a bit less transparent (there are two overlays visible when the Wallet Connect's modal is visible).

If the close button is still problematic I'm leaning toward just removing it. It's really difficult to get it working 100% well, and the cost / benefit for this is not worth it right now IMO (the same goes for the Wallet Connect's modal issues as long as the main functionality works).

We can create new issues for these problems and fix them later so we can move on now.

**Comment by gabitoesmiapodo** [comment]
@elena-zh 

> BTW, as you are working with walletconnect pop-up. is there any possibility to fix this issue #215 as well ?

I'd prefer to fix that later, it's not really a priority for now.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , 
Close button works well.
Modal is closed by clicking outside its area as well.
As for the last issue I have mentioned above, I will create a separate Low priority ticket for it.

Thanks!

**Review by elena-zh — APPROVED** [review]

**Pull request merged**
