### PR TITLE
Merge/Report payout  Feedback

### PR DESCRIPTION
**Pull request by mariano-aguero**
@hpmaxi Feedback
1 - Problem with disjoint https://github.com/gnosis/conditional-tokens-explorer/pull/571#discussion_r519036085
2 - Problem with filtering https://github.com/gnosis/conditional-tokens-explorer/pull/571#discussion_r519037847
3 - Problem with merge preview https://github.com/gnosis/conditional-tokens-explorer/pull/571#discussion_r519040191

@elena-zh Feedback https://github.com/gnosis/conditional-tokens-explorer/pull/571#issuecomment-723940788  
1 - Done
2 - This should be fixed with the point number 1 of Maxi's feedback
3 - Yes , we filter  positions with balance. Also the gnosis team suggested to allow to merge positions already resolved
4 - Should be fixed with the point number 1 of Maxi's feedback
5 - Idem 4
6 - Created an issue for this https://github.com/gnosis/conditional-tokens-explorer/issues/599
7 - Created an issue for this https://github.com/gnosis/conditional-tokens-explorer/issues/600
8 - The filter toggle of button, is overcharged with responsabilities. We decided to remove the confirm popup here, and in the report payout section too.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr598--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr598--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
Hi @mariano-aguero ,  I have reviewed the changes and have some points to discuss
1. The issue is still reproducible for me. I assume, that the pop-up is called due to positions list auto-loading runs each time on the page opening
2.  Fixed and works fine
3. Thanks for the explanation. However, it is a bit weird for me to see a position in the list that cannot me merged (it has 0.00 probability, that is why it is left with an amount)
image
image
4. The issue is still reproducible for me. Here is the transaction [details ](https://rinkeby.etherscan.io/tx/0x8ec6ddeba6162546492e0c360c9818edc55135ffdec7165486b9fba28b5a40c7)
5. The current case is fixed, However, I have caught [another error](https://rinkeby.etherscan.io/tx/0x93635120bf097bdf62f78efe14b5e899d66fd6cc42adea9af2565a08a8f706f4) when I was trying to reproduce the current one
6-7 will be checked after they are implemented
8. That's OK for me not to show the warning pop-up, but what about the 2nd case - to save the selection when switch the toggle off?

**Besides, I have found a few new issues:** 
9. checkbox in the Merge with section is shifted when a position preview is too long. I have added this case to #599 
10. the app is crashes when update a position/filter positions once a position from the Merge with section was selected (see the [video](https://drive.google.com/file/d/1VzgmeWBAfjfaN0EfX7ozlikZ6sS9mQ1A/view))
11. MERGED POSITIONS PREVIEW section is not updated/shows incorrect preview when update positions to merge (see the [video](https://drive.google.com/file/d/1UZ4bbayb1ED2ooY9vkHVRGpyjAcurXLX/view))

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr598--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr598--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gabitoesmiapodo** [comment]
https://github.com/gnosis/conditional-tokens-explorer/issues/599#issuecomment-725342634 should be fixed now.

Screen Shot 2020-11-11 at 13 55 55

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr598--conditionaltokensexplorer.review.gnosisdev.com

**Comment by mariano-aguero** [comment]
> Hi @mariano-aguero , I have reviewed the changes and have some points to discuss
> 
> 1. The issue is still reproducible for me. I assume, that the pop-up is called due to positions list auto-loading runs each time on the page opening

Is a cache issue

> 3. Thanks for the explanation. However, it is a bit weird for me to see a position in the list that cannot me merged (it has 0.00 probability, that is why it is left with an amount)

Seems to be dust, however is more than 0 so must be listed

> 4. The issue is still reproducible for me.
>    4.1.Here is the transaction [details ](https://rinkeby.etherscan.io/tx/0x8ec6ddeba6162546492e0c360c9818edc55135ffdec7165486b9fba28b5a40c7)
>    4.2. or these [details ](https://rinkeby.etherscan.io/tx/0xc2ee716034772bb1391b884a44423916cae9725b4844c3cd11aefff156eab346). This  result appeared when I tried to merge 'already merged' position with the 2nd condition
>    image
>    image

I tried this:
- I prepared a condition with 4 outcomes
- I splitted the condition in 4 positions
- I merged positions 0, 1, 3 in a new position
- I merged the new position from the previous step, with the position 2, so I have a new position 0,1,2,3

This worked for me, can you recheck or clarify step by step what you did to generate that error ?



> 5. The current case is fixed, However, I have caught [another error](https://rinkeby.etherscan.io/tx/0x93635120bf097bdf62f78efe14b5e899d66fd6cc42adea9af2565a08a8f706f4) when I was trying to reproduce the current one

Seems to be and edge case, can you create an issue for this with more information about how you generate that error ?

>    pp. 6-7 will be checked after they are implemented
>    p. 8. That's OK for me not to show the warning pop-up, but what about the 2nd case - to save the selection when switch the toggle off?
> 

Mmm seems to be an enhancement, we can live with that, maybe you can create an  issue for this

> **Besides, I have found a few new issues:**
> 9. checkbox in the Merge with section is shifted when a position preview is too long. I have added this case to #599

Will be fixed in #599 

> 10. the app is crashes when update a position/filter positions once a position from the Merge with section was selected (see the [video](https://drive.google.com/file/d/1VzgmeWBAfjfaN0EfX7ozlikZ6sS9mQ1A/view))

Fixed

> Also, the app is crashed after a successful position merge (when I close the confirmation pop-up)

Fixed

> 11. MERGED POSITIONS PREVIEW section is not updated/shows incorrect preview when update positions to merge (see the [video](https://drive.google.com/file/d/1UZ4bbayb1ED2ooY9vkHVRGpyjAcurXLX/view))

Fixed

**Comment by gabitoesmiapodo** [comment]
@mariano-aguero @elena-zh It's not necessary to create yet another issue about the filters / filter removal / etc.

I'm working on that here https://github.com/gnosis/conditional-tokens-explorer/issues/463 and hopefully we'll get a nicer workflow from that.

**Comment by gabitoesmiapodo** [comment]
@elena-zh @mariano-aguero `#9` should already be addressed on this same PR https://github.com/gnosis/conditional-tokens-explorer/pull/598#issuecomment-725538645

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr598--conditionaltokensexplorer.review.gnosisdev.com

**Comment by mariano-aguero** [comment]
Regarding this comment about the report payout https://github.com/gnosis/conditional-tokens-explorer/pull/582#issuecomment-725379376 , seems to be some feedback not finished. So I will work on this in this PR

> 2.1 It is allowed to enter a negative amount into the field (on the current version '-' is not allowed to be entered)

Done

> 2.2. there is no 0.00 placeholder in the fields when they are empty (they are exist in the current version)

Done

> 2.3. there is no validation 'At least one payout must be positive' when clear out all the fields (like it is on the current version)

Done

> 4 The issue is fixed. However, the screen is blinking on the Report payout page right after navigating to the page. See the video

Can you verify this one again ? I think is already fixed, didn't happen again in my machine

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr598--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr598--conditionaltokensexplorer.review.gnosisdev.com

**Comment by hpmaxi** [comment]
@mariano-aguero 

- After uncheck a position from the `merge with` box, you can still merge but with an error (Example tx: 0x986d8bc53e23daa6a20b5a5c32d3ea1665a0d8e4998d840b53f9c1bc4bd1f8bb )

failing-tx

- After input in position box there is a few seconds until the position searched is visible 

loading

- As in the previous bug/glitch there is a situation when you search for a position id but you don't receive the results. Maybe a race condition in an effect.
weird-bug

- The merge with list positions with zero balance, they seem to be listed because the graph isn't indexing fast enough. But the balance should come onchain so it kind of a weird bug too. This is fixed after refreshing. 

Captura de pantalla de 2020-11-11 16-54-41


Captura de pantalla de 2020-11-11 16-55-12

**Comment by hpmaxi** [comment]
Related to comment in #488 , this is still reproducible. 

I've prepared a new condition `0xd688061b92a2d45202efa603bd1d6f818e736e53dbcaf19a6a8a70b55f889098` and without refreshing between I get transaction failed. And for some reason the report has an empty array, this is the tx: `0xd89f55094e0949e035da68910c37e44357379e7eb992ba11c05d125de976bfbf` 

Captura de pantalla de 2020-11-11 18-04-21

After it, the list of possible conditions maintains unchanged, so I can select the same condition (or put it on the input condition), this tx fails `0x51fd5aa39705651bcb83d5fc16fe189ff3758f18ba87fc6b04a3a5f651395704` .

Captura de pantalla de 2020-11-11 18-06-15

I was able to get an error after reporting twice, but only once, https://dashboard.tenderly.co/tx/rinkeby/0x8ac6b1906c0b35a25b5e8b923d1e0ab83a8829b6578554fc3e1d19c764914643 the error is different.

**Comment by elena-zh** [comment]
> @elena-zh Regarding this comment about the report payout [#582 (comment)](https://github.com/gnosis/conditional-tokens-explorer/pull/582#issuecomment-725379376) , seems to be some feedback not finished. So I will work on this in this PR
> 
> > 2.1 It is allowed to enter a negative amount into the field (on the current version '-' is not allowed to be entered)
> 
> Done
> 
> > 2.2. there is no 0.00 placeholder in the fields when they are empty (they are exist in the current version)
> 
> Done
> 
> > 2.3. there is no validation 'At least one payout must be positive' when clear out all the fields (like it is on the current version)
> 
> Done
> 
> > 4 The issue is fixed. However, the screen is blinking on the Report payout page right after navigating to the page. See the video
> 
> Can you verify this one again ? I think is already fixed, didn't happen again in my machine

@mariano-aguero , I have verified the issues. Good job! Some minor cases: 
2.3. validation message 'At least one payout must be positive' is displayed under payouts section. However, on the current app versions it is hidden until a user fills in any payout field and then clears it out (when all the payouts fields have 0 value). Could you please fix it? 
 4. the screen is still blinking on the Report payout page right after navigating to the page from a conditions list/condition details page

**Comment by elena-zh** [comment]
> > Hi @mariano-aguero , I have reviewed the changes and have some points to discuss
> > 
> > 1. The issue is still reproducible for me. I assume, that the pop-up is called due to positions list auto-loading runs each time on the page opening
> 
> Is a cache issue
> 
> > 1. Thanks for the explanation. However, it is a bit weird for me to see a position in the list that cannot me merged (it has 0.00 probability, that is why it is left with an amount)
> 
> Seems to be dust, however is more than 0 so must be listed
> 
> > 1. The issue is still reproducible for me.
> >    4.1.Here is the transaction [details ](https://rinkeby.etherscan.io/tx/0x8ec6ddeba6162546492e0c360c9818edc55135ffdec7165486b9fba28b5a40c7)
> >    4.2. or these [details ](https://rinkeby.etherscan.io/tx/0xc2ee716034772bb1391b884a44423916cae9725b4844c3cd11aefff156eab346). This  result appeared when I tried to merge 'already merged' position with the 2nd condition
> >    image
> >    image
> 
> I tried this:
> 
> * I prepared a condition with 4 outcomes
> * I splitted the condition in 4 positions
> * I merged positions 0, 1, 3 in a new position
> * I merged the new position from the previous step, with the position 2, so I have a new position 0,1,2,3
> 
> This worked for me, can you recheck or clarify step by step what you did to generate that error ?
> 
> > 1. The current case is fixed, However, I have caught [another error](https://rinkeby.etherscan.io/tx/0x93635120bf097bdf62f78efe14b5e899d66fd6cc42adea9af2565a08a8f706f4) when I was trying to reproduce the current one
> 
> Seems to be and edge case, can you create an issue for this with more information about how you generate that error ?
> 
> > pp. 6-7 will be checked after they are implemented
> > p. 8. That's OK for me not to show the warning pop-up, but what about the 2nd case - to save the selection when switch the toggle off?
> 
> Mmm seems to be an enhancement, we can live with that, maybe you can create an issue for this
> 
> > **Besides, I have found a few new issues:**
> > 9. checkbox in the Merge with section is shifted when a position preview is too long. I have added this case to #599
> 
> Will be fixed in #599
> 
> > 1. the app is crashes when update a position/filter positions once a position from the Merge with section was selected (see the [video](https://drive.google.com/file/d/1VzgmeWBAfjfaN0EfX7ozlikZ6sS9mQ1A/view))
> 
> Fixed
> 
> > Also, the app is crashed after a successful position merge (when I close the confirmation pop-up)
> 
> Fixed
> 
> > 1. MERGED POSITIONS PREVIEW section is not updated/shows incorrect preview when update positions to merge (see the [video](https://drive.google.com/file/d/1UZ4bbayb1ED2ooY9vkHVRGpyjAcurXLX/view))
> 
> Fixed

@mariano-aguero , all the fixes and explanations (1-3, 8-11) LGTM. 
I will try to reproduce the cases in pp.4-5 and provide more details about them as soon as theGraph comes alive again.

**Comment by elena-zh** [comment]
@mariano-aguero , some more details for the: 
case 4.1 - please, create a condition and split positions for it. then select any position and split it again with the same condition. then, try to merge positions from the 2nd split. The system should not allow to merge positions of a 'deeper' level. but it is allows, that is why I get the 'disjoint' error
case 4.2: 
image

case 5 is not reproducible for me so far

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr598--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr598--conditionaltokensexplorer.review.gnosisdev.com

**Comment by mariano-aguero** [comment]
> @mariano-aguero
> 
> * After uncheck a position from the `merge with` box, you can still merge but with an error (Example tx: 0x986d8bc53e23daa6a20b5a5c32d3ea1665a0d8e4998d840b53f9c1bc4bd1f8bb )
> 
> failing-tx
> 


Done

> * After input in position box there is a few seconds until the position searched is visible
> 
> loading
> 


I reduce de debounce callback


> * As in the previous bug/glitch there is a situation when you search for a position id but you don't receive the results. Maybe a race condition in an effect.
>   weird-bug


Fixed with point before


> * The merge with list positions with zero balance, they seem to be listed because the graph isn't indexing fast enough. But the balance should come onchain so it kind of a weird bug too. This is fixed after refreshing.
> 
> Captura de pantalla de 2020-11-11 16-54-41
> 
> Captura de pantalla de 2020-11-11 16-55-12

I can't reproduce the problem, I need more information about it, if not you can create another issue for this (please with more information)

**Comment by mariano-aguero** [comment]
> Related to comment in #488 , this is still reproducible.
> 
> I've prepared a new condition `0xd688061b92a2d45202efa603bd1d6f818e736e53dbcaf19a6a8a70b55f889098` and without refreshing between I get transaction failed. And for some reason the report has an empty array, this is the tx: `0xd89f55094e0949e035da68910c37e44357379e7eb992ba11c05d125de976bfbf`
> 
> Captura de pantalla de 2020-11-11 18-04-21
> 
> After it, the list of possible conditions maintains unchanged, so I can select the same condition (or put it on the input condition), this tx fails `0x51fd5aa39705651bcb83d5fc16fe189ff3758f18ba87fc6b04a3a5f651395704` .
> 
> Captura de pantalla de 2020-11-11 18-06-15
> 
> I was able to get an error after reporting twice, but only once, https://dashboard.tenderly.co/tx/rinkeby/0x8ac6b1906c0b35a25b5e8b923d1e0ab83a8829b6578554fc3e1d19c764914643 the error is different.

Mmmm I can't reproduce this problem, I never get an empty array. The problem with reporting the condition twice, we can't resolve, because the indexer is not doing the job fast enough (if we trigger a refetch, we get the same information)
I'm ok with this because if you try again the same condition, will fail

**Comment by mariano-aguero** [comment]
> > @elena-zh Regarding this comment about the report payout [#582 (comment)](https://github.com/gnosis/conditional-tokens-explorer/pull/582#issuecomment-725379376) , seems to be some feedback not finished. So I will work on this in this PR
> > > 2.1 It is allowed to enter a negative amount into the field (on the current version '-' is not allowed to be entered)
> > 
> > 
> > Done
> > > 2.2. there is no 0.00 placeholder in the fields when they are empty (they are exist in the current version)
> > 
> > 
> > Done
> > > 2.3. there is no validation 'At least one payout must be positive' when clear out all the fields (like it is on the current version)
> > 
> > 
> > Done
> > > 4 The issue is fixed. However, the screen is blinking on the Report payout page right after navigating to the page. See the video
> > 
> > 
> > Can you verify this one again ? I think is already fixed, didn't happen again in my machine
> 
> @mariano-aguero , I have verified the issues. Good job! Some minor cases:
> 2.3. validation message 'At least one payout must be positive' is displayed under payouts section. However, on the current app versions it is hidden until a user fills in any payout field and then clears it out (when all the payouts fields have 0 value). Could you please fix it?

Done

> 4. the screen is still blinking on the Report payout page right after navigating to the page from a conditions list/condition details page

I wasn't able to reproduce the problem

Peek 12-11-2020 16-33
Peek 12-11-2020 16-34

**Comment by mariano-aguero** [comment]
> @mariano-aguero , some more details for the:
> case 4.1 - please, create a condition and split positions for it. then select any position and split it again with the same condition. then, try to merge positions from the 2nd split. The system should not allow to merge positions of a 'deeper' level. but it is allows, that is why I get the 'disjoint' error
> case 4.2:
> image
> 
> case 5 is not reproducible for me so far

Mmmm can you create an issue for the case 4.1 and 4.2 ? seems to be a weird problem, and maybe we can work on this in a particular issue

**Review by hpmaxi — APPROVED** [review]

**Comment by elena-zh** [comment]
HI @mariano-aguero , I have rechecked the fixes. Great job! Some notes: 
1. issue for the case 4.1 - #612 
2. issue for the case 4.2 - #611
3. I have found an issue with filters section on the Merge positions page - search results are reset when switch on/off filter toggle. See the [video](https://drive.google.com/file/d/1W50sJoJoYj7GGbVkyInbul1RyF3ML1g-/view)
4. p4 (search blinking on the report payouts) is not reproducible for me so far. 
5. p2.3. (warning message for report payouts) is not exactly works as it worked on the previous app version. See the [video ](https://drive.google.com/file/d/1O46Y4Kdsfj_4bH1yZcnJR3hMnCuKpAP6/view)with what I expect to get 
6. I have created a rounding issue for the merge preview section (as it was applicable for the previous app version as well) - #613
7. I also faced the issue with 0 amounts positions in the Merge with section (described by @hpmaxi  above). However, it seems to me that the issue is reproducible only when theGraph goes down and the merged positions are not yet zero out in the DB after the merge.

**Pull request merged**
