### PR TITLE
[FE] Redeemed position returns no tokens

### LINKED ISSUE #314: [FE] Redeemed position returns no tokens
The case is:
I resolve a condition with probabilities:
Outcome 0 - 100%
Outcome 1 - 0%
When I redeem the 1st position and return back all the 100% tokens, I still see the 2nd position with 0% probability.
I CAN redeem it, but the transaction seems to be useless as no tokens will be returned to my wallet, and I will pay a gas fee. However, if I do not redeem the position, it will be always shown in the positions list with not zero amount.

It would be nice to add a warning message that a position will return no tokens to the wallet.

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #314

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr808--conditionaltokensexplorer.review.gnosisdev.com

**Review by elena-zh — CHANGES_REQUESTED** [review]
@mariano-aguero . here are some issues from my side: 
1. It would be noce to add a period in the end of the warning message
add a period

2. Do not shoe the warnong section when a redeemed position preview is loaded (currently, the section blinks)
https://drive.google.com/file/d/1VCgZN82ofCbd2wqcCaOI78ULQdM6hvi8/view

3. No to show the warning message when redeem a position of a 'deeper' level
image

Could you please fix all these issues?

**Comment by mariano-aguero** [comment]
> @mariano-aguero . here are some issues from my side:
> 
> 1. It would be nice to add a period in the end of the warning message
>    add a period
> 2. Do not shoe the warning section when a redeemed position preview is loaded (currently, the section blinks)
>    https://drive.google.com/file/d/1VCgZN82ofCbd2wqcCaOI78ULQdM6hvi8/view
> 3. No to show the warning message when redeem a position of a 'deeper' level
>    image
> 
> Could you please fix all these issues?

Fixed!

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr808--conditionaltokensexplorer.review.gnosisdev.com

**Review by elena-zh — APPROVED** [review]
Works fine now!

**Pull request merged**
