### PR TITLE
(Feature) Wrap and unwrap modals

### LINKED ISSUE #193: [UI/UX] - Wrap / Unwrap modals
Design: https://zpl.io/a8grerx / https://zpl.io/bJyELkn

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #193 

A few notes about this:

- Wrap and Unwrap functionality is not implemented yet, that will be done on https://github.com/gnosis/conditional-tokens-explorer/issues/187
- **"ERC1155"** value should be correct, but **"ERC20"** is mocked to test the workflow.
- Implemented two possible workflows: 
-- Click "Wrap" / modal opens / fill the textfield / click "Wrap" / status info window shows "Working" message and icon / wait for 5 seconds / "Success" message and icon should appear / click "OK" / status info window should close.
-- Click "Unwrap" / modal opens / fill the textfield, click "Unwrap" / status info window shows "Working" message and icon / wait for 5 seconds / "Error" message and icon should appear / click Close / status info window should close.

We can add more detailed info for the working / error statuses when the missing logic is implemented.

**Workflows:**

Sep-11-2020 16-00-02

Sep-11-2020 16-00-09

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr235--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr235--conditionaltokensexplorer.review.gnosisdev.com

**Review by mariano-aguero — APPROVED** [review]

**Comment by elena-zh** [comment]
I have verified the changes and have found some issues: 
1. Impossible to enter an amount manually into the field
2. It is possible to go back when the spinner is displayed --> a user will never know about the result of the transaction
https://drive.google.com/file/d/1lc6x17LqC3YyCnrQZQppO6Jo8UBtDsoA/view
3. The actions are available to a not logged in user. However, the COLLATERAL WRAPPING  section is also displayed on the position detail page, and that is strange as we hide amounts on the Positions list when a user is not logged in. So, here we have to decide whether hide the section at all (and wrap/unwrap action buttons from a position list) to a not logged in user OR just call the connection window when user presses on 'Wrap'/'Unwrap' buttons
can unwrapp unlogged

hide section

not logged in - hide

**Review by hpmaxi — APPROVED** [review]

**Comment by gabitoesmiapodo** [comment]
@elena-zh 

1- Which field? I found a problem when trying to enter numbers that start with zero (ie: `0.3`, or whatever), but I forgot to report that. Had no problems with other numbers.
2- Yeah, thats a normal "problem" with dapps. I don't think there's much we can do about that, as we can't disallow the user to navigate to other page, or close to even the browser. Transactions' results can be seen on the wallet's log, though.
3- This is a valid point, but we are going with the "show everything to the user, ask them to login when needed" route, so I don't think we should hide anything here. Disabling the "Wrap" / "Unwrap"  buttons should be enough, I think. Regarding the menu: I think it can't be done, or it's really complicated to do it, so that's why the guys aren't disabling the actions there (we can confirm that with @mariano-aguero and @hpmaxi).

**Comment by elena-zh** [comment]
@gabitoesmiapodo , 
1.  Amount field. And yes, I cannot enter a value which starts with 0
2. Thanks for the explanation
3. Collateral wrapping amounts are not the same for different users. Here is an example: different data s displayed for different accounts. That makes me think that Amounts data is a sensitive one. That is why I have a proposal to hide this section at all. 
1st account

2nd account

Regarding the menu: we have a note on the mock-up https://zpl.io/2ENrpny which advises to disable/hide an option if it is not available. So, it would be nice to hide/disable these actions in grid in order to follow a common logic.

**Comment by gabitoesmiapodo** [comment]
@elena-zh Ah, yes, I remember now (about the note). I think we discussed this with @hpmaxi and @mariano-aguero and found it was easier to do it the way it is implemented now.

Regarding the amounts issue: maybe we can show some kind of text, like "Connect to a wallet to display", or something like that?

**Comment by elena-zh** [comment]
@gabitoesmiapodo , it will be fine to show such a message in the section. 
Should we create a separate task for it or it will be fixed under the current issue?

**Comment by gabitoesmiapodo** [comment]
@elena-zh please add it in a comment here https://github.com/gnosis/conditional-tokens-explorer/issues/187

**Pull request merged**
