### PR TITLE
(fix) modal's title line height

### LINKED ISSUE #360: [UI/UX] Merge positions pop-up: letters in the header are truncated
See the pic: 

Reproducible in the last vetstion of Chrome, scale >80%, screen resolution 1536x712

When screen resolution is 1920x927, the issue is reproducible when scale is 80-90%

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #360

I still can't reproduce the issue, but increased line height a little more.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr380--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gabitoesmiapodo** [comment]
@elena-zh if this is OK please approve it so I can merge it into `/develop`

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr380--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gabitoesmiapodo** [comment]
@elena-zh Sorry to open this again, but it needs to be approved by you so I can merge it into develop before closing it.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr380--conditionaltokensexplorer.review.gnosisdev.com

**Review by elena-zh — APPROVED** [review]

**Comment by elena-zh** [comment]
I'm sorry @gabitoesmiapodo  for not noticing it. 
Approved. Thanks!

**Pull request merged**
