### PR TITLE
(Feature) Select condition

### LINKED ISSUE #72: [UI/UX] - Split Position - Select Condition
- Columns to show - TBD
- Add button in Split Position
- Create new modal
- Table (similar to condition list)
- Search and filter
- Select condition on click
- Submit

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #72

**Screenshots:**

Screen Shot 2020-08-26 at 19 38 12
Screen Shot 2020-08-26 at 19 38 20
Screen Shot 2020-08-26 at 19 38 24
Screen Shot 2020-08-26 at 19 39 18
Screen Shot 2020-08-26 at 19 39 25
Screen Shot 2020-08-26 at 19 39 31

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr145--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr145--conditionaltokensexplorer.review.gnosisdev.com

**Comment by lmcorbalan** [comment]
I think styles in `Condition List` and `Position List` got broken
image
image

**Comment by gabitoesmiapodo** [comment]
> I think styles in `Condition List` and `Position List` got broken

@lmcorbalan ah, yeah... fixed!

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr145--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr145--conditionaltokensexplorer.review.gnosisdev.com

**Pull request merged**
