### PR TITLE
Link to oracle if it is known

### LINKED ISSUE #538: Display oracle = realit.io for a position when it belongs to an omen condition
Related to #527, #355
When we create an omen condition we show oracle = realit.io. 
When we open a related position details, we see oracle = 0x576b76eebe6b5411c0ef310e65de9bff8a60130f . 
**Expected Result**: to show oracle = realit.io in the position's details as well

**Note**: Names (realit.io) should be shown in the lists too

### LINKED ISSUE #540: Link to oracle if it is known
On the condition and position screens, we should link to the URL the oracle if it is known.

In the case of reality.eth, we should link to the specific question.

e.g. for this condition, the "Reality.io" text should link to `http://reality.eth.link/app/#!/question/0x4cdfa97977c9752263a6774989aa8701569bcd5eb26721c4c8c479c085e996ba`

Side note, we should update all references to `reality.io` to `reality.eth`

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #538 
Closes #540 

Look like this

Screenshot_20201029_165225
Screenshot_20201029_165344
Screenshot_20201029_165321
Screenshot_20201029_165236

### CODE REVIEW

**Comment by mariano-aguero** [comment]
Please DONT MERGE this PR until David is available, This PR change the name of some env vars and we need to update them in the server

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr557--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
Hi @mariano-aguero , the changes look great to me. 
However, it would be nice to display reality.eth as an oracle for Omen conditions in the Select condition pop-up as well.


Also, it seems than sorting for the oracle column works based an oracle address (not based on the oracle name itself). So, as it was discussed in #340, it would be nice to disable sorting for this column in order to prevent this issue

**Comment by gabitoesmiapodo** [comment]
@mariano-aguero @elena-zh just to prevent you working on something that's not going to exist anymore in a few days: don't change anything in the select conditions' / select positions' tables.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , yes, sure. Thank you for noticing!
However, in a 'new' conditions section the 'Reporter/Oracle' column exists. We should not forget to display reality.eth as an oracle for Omen conditions there as well.

**Review by gabitoesmiapodo — APPROVED** [review]
It works great.

Maybe in the future we should make the search option "Oracle address" just "Oracle" so the users can search by writing the oracle's address or name. I don't know if it's possible, though.

**Comment by elena-zh** [comment]
> Maybe in the future we should make the search option "Oracle address" just "Oracle" so the users can search by writing the oracle's address or name. I don't know if it's possible, though.

We can add this search option to the #409 and #414

**Comment by mariano-aguero** [comment]
> @gabitoesmiapodo , yes, sure. Thank you for noticing!
> However, in a 'new' conditions section the 'Reporter/Oracle' column exists. We should not forget to display reality.eth as an oracle for Omen conditions there as well.
> 

You can write a comment here, so we can implement this https://github.com/gnosis/conditional-tokens-explorer/issues/511

**Comment by elena-zh** [comment]
> > @gabitoesmiapodo , yes, sure. Thank you for noticing!
> > However, in a 'new' conditions section the 'Reporter/Oracle' column exists. We should not forget to display reality.eth as an oracle for Omen conditions there as well.
> > 
> 
> @elena-zh You can write a comment [here](https://github.com/gnosis/conditional-tokens-explorer/issues/511), so we can implement this

Done!

**Comment by elena-zh** [comment]
Verified in Dev. 
Issue to disable sorting for the Reporter/Oracle column in the conditions list is created - #562

**Pull request merged**
