### PR TITLE
(Feature) Cookies / Google Analytics (Accept / Refuse)

### LINKED ISSUE #756: Update cookie banner
The current cookie banner gives users the option to accept or dismiss the banner.
image

This needs to be updated so that:
1. Analytics cookies (GA) are disabled by default, but can be opted in to.
2. Any necessary cookies cannot be deselected.

See this example from Gnosis Safe
image
And this example from another product
image

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #756

Changed things a lot to achieve this.

**The intended behaviour is:**

- **Mandatory cookies** (ie: wallet connection, cookies settings, columns settings, etc.): users can't opt out or change anything. They are used whether the user closes the cookies window or not, or whether they click "Accept All" or not.
- **Google Analytics:** activated and used when the user clicks "Accept All". **Note:** remember `REACT_APP_GOOGLE_ANALYTICS_ID` must be set for this to work.
- **Accept All:** checks all the checkboxes and closes the cookies window.
- If "Analytics" is checked and then the cookies window is closed using the top right `X` Google Analytics won't be activated.
- The users can change this at any moment using the "Settings" icon next to "Cookie Policy" at the bottom. **For example:** to disable "Analytics" the user would click on "Settings", then uncheck "Analytics", and finally they should close the window using the top right `X`... convoluted, I know, but it's more or less how it works on Gnosis Safe.

**Screenshots:**

Screen Shot 2020-12-22 at 12 32 22

Screen Shot 2020-12-22 at 13 01 59

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr775--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr775--conditionaltokensexplorer.review.gnosisdev.com

**Review by hpmaxi — APPROVED** [review]

**Review by mariano-aguero — APPROVED** [review]
LGTM

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr775--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
Works fine. 
However, 'Accept Preference' button is missing for me here. At least, I an used to clicking on a button on other sites in order to accept cookies policy (and not just close a banner)...

**Pull request merged**
