### PR TITLE
(QA) Edit partition bugs

### LINKED ISSUE #253: Partition section - Edit partition bugs
Related to #237 , #66 , #67 , #65 , #160

1. Empty rows are displayed in the section when drag and drop all the outcomes and then click on the reset button (see the video)
https://drive.google.com/file/d/1DJeNOQ5emlvRIEjTfz2HK1-7UDe_p-ta/view

2. Empty rows are displayed in the section when replace an outcome into Outcomes section by **clicking on the outcome circle** and then click on the reset button 

3. The system allows to save a partition with only one collection in it: repeat steps 1 or 2 of the current issue, an then, then there is only one outcome and 1 empty line, click on the Save button (see the video). The transaction for positions creating will be finished with failure
https://drive.google.com/file/d/1-hYTJCH9QatnUD1HNiUX7jaDeXPk9PkO/view

4. Numbers do not fit the circle area when a condition contains outcomes more than 100 outcomes (3-digits outcomes)

5. The edited partitioning before login is not saved after a user logs in (see the video) Note: the issue with amount field on the video is described here: #252
https://drive.google.com/file/d/1HscxRWRKrSb8_e1AOgjIt_QYhaMJo04-/view

6. Bin icon is still displayed when drag and drop a position (should not be displayed according to the mock-up (https://zpl.io/aR5Z76K)

7. a Circle in the New collection prevoew field should be in red when hover a mouse on it according to the mock-up (https://zpl.io/aR5Z76K)

8. No horizontal lines should be displayed in the partition when it contains a lot of outcomes, placed one after another according to the mock-up (https://zpl.io/aR5Z76K)

9. 'Move' and 'Bin' icons should be top-aligned when outcomes exceed 1 line (mock-up https://zpl.io/aR5Z76K)

10. New collection preview should contain the lines between the outcomes according to the mock-up https://zpl.io/V039zl9

11. There is no confirmation before removing New Collection Preview. It should be according to the mock-up https://zpl.io/a3WXQZx

12. It would be nice not to order outcommes in ASC order when move them into the New Collection Preview field (it will be diffiecuit to a User to create a 'right' collection). See the video
https://drive.google.com/file/d/14ilfd1Fh2HQwusey4mMTmwQLUj0homEA/view

13. No ability to create a separate collection using drag and drop functionality for an outcome

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #253

There's still some work missing on #253, but I'm creating this to have a preview available.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr263--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr263--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr263--conditionaltokensexplorer.review.gnosisdev.com

**Comment by mariano-aguero** [comment]
@elena-zh Points 1, 2 and 3 was fixed, Can you create a separated issue for the issue number 5? Thanks

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr263--conditionaltokensexplorer.review.gnosisdev.com

**Review by hpmaxi — APPROVED** [review]

**Review by mariano-aguero — APPROVED** [review]

**Pull request merged**
