### PR TITLE
Add check condition not resolved in `InputCondition` hook

### LINKED ISSUE #209: User is not warned when tries to split position for a resolved condition
**Steps:** 
1. Create a condition + Positions for it
2. Resolve the condition
3. Redeem positions
4. Open the Split position page
5. Fill in the Condition field with the resolved condition

**Actual Result** User is not  warned, that a condition is already resolved
(however, the system should allow to split positions for a resolved condition)

**Expected Result:** User should be warned, that a condition is already resolved

### PR DESCRIPTION
**Pull request by davidalbela**
Closes #209

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr267--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr267--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr267--conditionaltokensexplorer.review.gnosisdev.com

**Review by hpmaxi — APPROVED** [review]

**Review by hpmaxi — APPROVED** [review]
I'm not sure about the error styles but LGTM.

**Comment by mariano-aguero** [comment]
Look like this...
I'm a little concern about the size of the badge, and the position. Since there is no design for this (what is the correct place of the badge) I left to @gabitoesmiapodo the approve or not of this PR. Maybe place the badge up and to the right is better, but I don't know, I'm not an UX expert like gabriel

Screenshot_20200916_182055

**Review by gabitoesmiapodo — CHANGES_REQUESTED** [review]
Hm... this works. But it should look better 😄 

This shouldn't be a badge.

@davidalbela, check the way we display errors elsewhere in the app and display the same message as an error. You can look how we do it in the "Select Position" or "Select Condition" textfields. That should do it.

**Comment by gabitoesmiapodo** [comment]
I've been made aware that this shouldn't been displayed as an error but more as a warning to the user, so I've added this to the PR:

Screen Shot 2020-09-17 at 16 06 48

**Review by gabitoesmiapodo — APPROVED** [review]

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr267--conditionaltokensexplorer.review.gnosisdev.com

**Pull request merged**
