### PR TITLE
Details consistency related to omenMarkets and questions

### LINKED ISSUE #731: Inconsistency of the info in a condition and a related position details
Related to #628, #695

**Case 1. Omen condition without Omen markets**

Condition details look good. Section with Omen Markets is missing there, question section is displayed.
But when we open the related position details, we do not see the question here, but see the Omen markets section instead. Can we replace Omen markets section with Question section for the related position details?

**Case 2. Custom reporter condition**
We are able to see the Question section there.  
But when we open the related position details, Omen markets section is displayed there. Frankly, the Omen markets section for a custom reporter position looks bit weird.. Could it be replaced with Question section at least?

**As a note and an example:**  Omen condition and positions with Omen markets look good and consistent and do not require any changes

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #731 

To test this I've used 
```
REACT_APP_CTE_GRAPH_HTTP_RINKEBY='https://api.thegraph.com/subgraphs/name/davidalbela/conditional-tokens-rinkeby'
REACT_APP_CTE_GRAPH_WS_RINKEBY='wss://api.thegraph.com/subgraphs/name/davidalbela/conditional-tokens-rinkeby'
```

All new tests are ignored because I couldn't make them work properly. After the feedback, I will focus on test the changes on the presentational components only. The problems seem related to de MockProvider that ignores the use of our wrapper around different contexts for Omen and CTE. 

Both components are shown. It is simpler that way as discussed with @mariano-aguero , the data from the hooks is inside a container `OmenMarketsOrQuestions`, we can change that logic from there. Another solution is to move the logic to `Contents` but is not trivial enough to do that, I prefer to maintain a Container that fetches everything needed to make a decision about visibility. 

I wanted to push this with a test because I found that are multiple scenarios in which this looks different according to the data available, and mocked data should be able to do that job.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr762--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
Hi @hpmaxi !
From this PR I'm able to see, that all the sections have become consistent on different types of conditions and their positions. 
However, several questions: 
1. Now I'm able to see that 'Question' section contains an id. It will be replaced with a text, correct? If yes, displaying both sections (question and Omen markets) on an Omen condition details and its position will look a bit strange from my perspective, due to a question and omen markets texts will be the same. 
 image

The only case where we can leave displaying both question and Omen market sections for a **position id**, is when a position belongs to 2 conditions like: 
 - Omen condition with Omen market+Custom reporter condition 
 - Omen condition with Omen market+Omen condition without an Omen market.

2. When a position belongs to 2 conditions with different questions, Questions section should display all the questions texts and should be expanded (currently, it shows only one question)
2 condition

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr762--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gabitoesmiapodo** [comment]
Couldn't find anything besides what Elena found. So, fix those issues and then LGTM.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr762--conditionaltokensexplorer.review.gnosisdev.com

**Review by mariano-aguero — APPROVED** [review]

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr762--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
Verified and works great at almost all cases. 
The only case that it would be nice to fix is to show both Question and Omen Market section for a position which belongs to Omen condition **with** Omen market+Omen condition **without** an Omen market. I have created a separate issue for this exceptional case #774.

**Pull request merged**
