### PR TITLE
Clear amount on change of splitFrom

### LINKED ISSUE #159: [FE] Split position: If I changed from collateral to position tab/link, my balance amount was not reset
See https://github.com/gnosis/conditional-tokens-explorer/pull/155#issuecomment-685976155

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #159 

- [x] This should clear errors too, when you don't have balance for a position/collateral and change to a collateral/position with balance.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr161--conditionaltokensexplorer.review.gnosisdev.com

**Comment by lmcorbalan** [comment]
I doesn't seems to be working
splitPosition

**Comment by gabitoesmiapodo** [comment]
Seems to work for me, but check @lmcorbalan's comment above.

Sep-08-2020 09-28-39

**Review by gabitoesmiapodo — APPROVED** [review]

**Comment by lmcorbalan** [comment]
@gabitoesmiapodo Actually it isn't working for you neither, look at the `Use Wallet Balance` balance, it remains the same when you change from `COLLATERAL` to `POSITION`,  even when you haven't selected a position yet.

To me the expected behaviour would be like:
1- User enters Split Position section
   1.a - The sections shows `Split from COLLATERAL`
   1.B - `Use Wallet Balance` shows user's balance for selected TOKEN (by default it's DAI)
2- User change to `Split from POSITION`
  2.a - Amount input gets cleared
  2.b -  `Use Wallet Balance` shows 0, since there is no POSITION selected yet
  2.c - User selects a POSITION
    2.c.1 - `Use Wallet Balance` shows user's balance for the previous selected POSITION
3- User change to `Split from COLLATERAL`
  3.a - Amount input gets cleared
  3.b - `Use Wallet Balance` shows user's balance for selected TOKEN
4- User change to `Split from POSITION`
  4.a - Amount input gets cleared
  4.b - `Use Wallet Balance` shows user's balance for selected POSITION

... to the infinity and beyond

**Comment by gabitoesmiapodo** [comment]
@lmcorbalan 

Ah, yeah, I misunderstood what this was about. It needs fixing then.

**Review by gabitoesmiapodo — CHANGES_REQUESTED** [review]
See Lisandro's comments above.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr161--conditionaltokensexplorer.review.gnosisdev.com

**Review by mariano-aguero — CHANGES_REQUESTED** [review]
The feature is not working
Peek 08-09-2020 15-13

**Comment by hpmaxi** [comment]
I've forgotten to reset the amount to zero when a position is not set. This should work now.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr161--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — APPROVED** [review]

**Review by lmcorbalan — APPROVED** [review]

**Review by mariano-aguero — APPROVED** [review]

**Pull request merged**
