### PR TITLE
[FE] Edit / Remove outcomes is not working

### LINKED ISSUE #451: [FE] Edit / Remove outcomes is not working
This needs to be done after #443 and #449 are approved and merged.

- Go to "Prepare condition"
- Select "Omen Condition"
- Fill all the fields, do not add outcomes.
- Add three outcomes named "1", "2", and "3".
- Edit the names to "11", "22", "33", you'll see the changes on the screen.
- Click on "Prepare".

After the condition is created, you should see that the outcomes' names are still "1", "2", and "3". So: editing doesn't work.

The same should happen if you remove outcomes.

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #451 

Peek 14-10-2020 16-42

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr470--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr470--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — CHANGES_REQUESTED** [review]
Nice, this is working much better now.

A few problems I found and think should be fixed if possible:

**Removing items:**

- Add outcomes named `1`, `2`, `3`.
- Edit outcomes and rename to `11`, `22`, `33` (don't save the changes).
- Delete the outcome `22`

You'll end up with two outcomes: `11` (still not saved) and `3` (which now appears as saved, and with a wrong value), while you should end up with `11` and `33`

I tried a few more weird combinations of actions and they all seem to work fine.

**Unsaved outcomes:** (this is more of a question or a dilemma)

- Add some outcomes.
- Click on the "Edit button" in all of them, change the text. (Do not save any changes.
- Here's the catch: should we send the form anyways - unsaved changes and all- when clicking on "Prepare"? Should we warn the user that there are unsaved changes? Or do we disable the "Prepare" button until all changes are saved?

Whatever we decide, it could be implemented on another issue.

----

Unrelated issue (but it may be an easy fix?):

- The Category dropdown shows the "Bussiness & Finance" option as selected by default, but it should be "Arts" (the first one).

**Review by hpmaxi — APPROVED** [review]
In addOutcome the clone could be avoided, the rest operator and filter method can be leveraged to do the same without lodash in this case (array of strings), but in this way it works!

**Comment by mariano-aguero** [comment]
> Nice, this is working much better now.
> 
> A few problems I found and think should be fixed if possible:
> 
> **Removing items:**
> 
> * Add outcomes named `1`, `2`, `3`.
> * Edit outcomes and rename to `11`, `22`, `33` (don't save the changes).
> * Delete the outcome `22`
> 
> You'll end up with two outcomes: `11` (still not saved) and `3` (which now appears as saved, and with a wrong value), while you should end up with `11` and `33`
> 
> I tried a few more weird combinations of actions and they all seem to work fine.
> 

Fixed, I disabled the remove button


> **Unsaved outcomes:** (this is more of a question or a dilemma)
> 
> * Add some outcomes.
> * Click on the "Edit button" in all of them, change the text. (Do not save any changes.
> * Here's the catch: should we send the form anyways - unsaved changes and all- when clicking on "Prepare"? Should we warn the user that there are unsaved changes? Or do we disable the "Prepare" button until all changes are saved?
> 
> Whatever we decide, it could be implemented on another issue.
> 

Created an issue for this https://github.com/gnosis/conditional-tokens-explorer/issues/479


> Unrelated issue (but it may be an easy fix?):
> 
> * The Category dropdown shows the "Bussiness & Finance" option as selected by default, but it should be "Arts" (the first one).

Done!

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr470--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr470--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — APPROVED** [review]
🐻

**Comment by elena-zh** [comment]
The changes look good to me. 
#486 issue is created for a Category dropdown (might be related)

**Pull request merged**
