### PR TITLE
Add clear date to prepare condition

### LINKED ISSUE #617: [FE] Clear date value from Prepare Omen Condition section
_Originally posted by @elena-zh in https://github.com/gnosis/conditional-tokens-explorer/issues/531#issuecomment-718620039_

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #617 

I'm not sure where to put the "clear" text. I've used a component used for filters but maybe it should be right-aligned. The errors of `resolutionDate` are cleared too. 

 
Captura de pantalla de 2020-12-18 18-15-07

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr764--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gabitoesmiapodo** [comment]
> I'm not sure where to put the "clear" text. I've used a component used for filters but maybe it should be right-aligned. The errors of resolutionDate are cleared too.

Well... we have a component which specifically does that, and the input titles support it, so use it haha.

`TitleControlButton` is probably the best option here:

```
<TitleValue
  title="Resolution"
  titleControl={
    <TitleControlButton
      disabled={somConditionHere}
      onClick={clearTheDate}
    >
      Clear
    </TitleControlButton>
  }
  value={inputFieldGoesHere}
/>
```

Like on these:

Conditional_Tokens_Explorer_And_Factory
Conditional_Tokens_Explorer_And_Factory-2

**Comment by elena-zh** [comment]
In addition, it would be nice to have Clear button enabled when a value is 'incomplete'
image

**Comment by gabitoesmiapodo** [comment]
@hpmaxi @elena-zh 

Just checking (because I don't remember the details) but make sure that it works as in the filters.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr764--conditionaltokensexplorer.review.gnosisdev.com

**Comment by hpmaxi** [comment]
@elena-zh @gabitoesmiapodo Can you check again?. I've used the correct component now! I guess it was late last Friday :man_facepalming: but also my first attempt was to reuse `DateFilter` there.

**Comment by elena-zh** [comment]
@hpmaxi  , now everything looks great for me.
Thanks!

**Review by gabitoesmiapodo — APPROVED** [review]
giphy

**Pull request merged**
