### PR TITLE
'Are you sure you want to leave this page?' pop-up appears after successful position creation/merge

### LINKED ISSUE #560: 'Are you sure you want to leave this page?' pop-up appears after successful position creation/merge
Related to #211, #537

**Pop-up appears when:** 
 - split positions and then try to navigate to a position detail (in the same tab)

 - merge positions and then try to navigate to a position detail (in the same tab)

**Expected Result:** do not show the pop-up in the mentioned above cases

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #560 

Fixed for the split section, can't reproduce the problem in the merge section (maybe fixed in another PR)
@elena-zh can you verify the fix ? please approve it if is OK, thanks

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr699--conditionaltokensexplorer.review.gnosisdev.com

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hi @mariano-aguero , 
It works fine on the Split positions page. 
However, it is still reproducible for me on the Merge positions page
image

Could you please take a look?

**Comment by mariano-aguero** [comment]
> Hi @mariano-aguero ,
> It works fine on the Split positions page.
> However, it is still reproducible for me on the Merge positions page
> image
> 
> Could you please take a look?

@elena-zh fixed on the merge section too! thanks for the feedback

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr699--conditionaltokensexplorer.review.gnosisdev.com

**Review by elena-zh — APPROVED** [review]
Approved!
Thank you!

**Pull request merged**
