### PR TITLE
Use bn.js for indexsets

### LINKED ISSUE #261: [FE] Crash when splitting from a condition with more than 31 outcomes
[Updated in comment] 
I tried to create a set of positions from `0x23d70bb87090a316f7d03d9d5d8b3bd883af6672ebd583e013fafb8a070cca5a` using DAI as collateral. I went to edit partition, remove the trivial partition and start creating some collections. 

Captura de pantalla de 2020-09-15 15-17-11

After that, clicking in split gives me

Captura de pantalla de 2020-09-15 15-19-45

### LINKED ISSUE #487: Given 2 positions A and B|C their merge preview is wrong
The preview is shown as a shallower position but with two outcomes. 

https://gist.github.com/hpmaxi/7581b90947818737ceee9cc01640bbce

### LINKED ISSUE #490: [FE] Crash when splitting from a condition with many outcomes
When splitting a position from a condition with many outcomes (for example 61 as with condition `0xe4fc24ff668887733b96bd928ccaf715e2c7f9331b32352ece3178820459cfa7`) the app will crash with an error like this one:

- Go to "Split Position" 
- Fill in "Condition ID" with `0xe4fc24ff668887733b96bd928ccaf715e2c7f9331b32352ece3178820459cfa7`  (or any other condition with a substantial amount of outcomes).
- Fill every other input.
- You can also edit the partition, but it's not necessary.
- Click split.

Tried this with (all have more than 31 outcomes): 

`0xe4fc24ff668887733b96bd928ccaf715e2c7f9331b32352ece3178820459cfa7` `0xf1c1075bc6e88dc4e848934e6f0148c9c40003c2ab63d634e5c76d46c5e07bf0`
`0xecab5c10f281a3299f17aab702c24543c6f9f2ada83922c5fe934d749a32d142`
`0xceb9e06e8fdb33faef4f65a1af5ef1e33bb24305eb84ade492bd78fa3c38ed7f`

From 31 outcomes and below it seems to work fine:

`0x63c36521ce93b8d1c1302168bcc4bdf06949bd93e2c1653780a7dc4d3a1aa9f2`

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #261 
Closes #490 
Closes #487 (I've tested this one with another set of positions different than the ones listed in the gist of the description).

This solves a javascript limitation for operating numbers larger than 2^32 (The limit is bigger but not for bitwise operations), details are in the comments of #261. To circumvent that problem we add `bn.js` and use internally to operate between ` `indexSets` using a set of helpers, everything else receives and returns strings. If we need to change to another library in the future we only need to change those helpers and maintain the contract of using strings as an intermediate representation.

I also tried to avoid code duplication and make it clearer his intentions, with comments, refactors, etc. This still has room for improvement, maybe namespacing tools related to partitions/indexSets/etc. and some functions that do almost the same with little differences that could be composed, some missing tests, etc.

To verify the binary representation I used [numberfacts](https://www.numberfacts.com), and for rinkeby I used this condition `0x2abbbe9454d3becd885d6f64946105c3d2345a64d08d39a5ea634a9e3e55b32a` with 35 outcomes and `0x25c131e286f4ec0bf939fe3f2d68454f1936a3660902c5a480228a47f6c8400b` with 120 outcomes. 

There are two possible issues, @mariano-aguero @gabitoesmiapodo 
- [ ] https://rinkeby.etherscan.io/tx/0x29ee06482b5a1b2d9a03d0c4559f335254934fb61af698f9433581beb49e1260 for many different outcomes the split run out of gas. Is not a problem with the number of outcomes because with smaller sets this is not happening (I've made a split with three outcomes as in the attached screenshot).
- [ ] For many outcomes, when you scroll to the bottom and try to delete all outcomes the prompt for deletion appears on top so is not visible at first sight (you need to scroll to the top again).

Captura de pantalla de 2020-10-29 14-55-44
Captura de pantalla de 2020-10-29 14-56-02

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr550--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr550--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr550--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — APPROVED** [review]
giphy-downsized

It works fine.

I'm OK with the small issues, we can fix them later.

**Comment by mariano-aguero** [comment]
@hpmaxi please solve the conflicts, thanks

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr550--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
Verified. 
Works pretty fine except the known issues: 
#313 - incorrect fields' values on the redeem position preview
#574 - Transaction fails (split run out of gas) when split a condition with more than 69 positions (described above)
#575 - Confirmation message to delete outcomes is not visible when there too many outcomes in the partition section (described above)

**Pull request merged**
