### PR TITLE
Question integration

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes several issues...

### CODE REVIEW

**Comment by mariano-aguero** [comment]
Blocked by https://github.com/gnosis/hg-subgraph/issues/34

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr737--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr737--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr737--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
Hi @mariano-aguero !
It might be a bit a bit early to check, but I have done some tests and here are my notes: 
1. It would be nice to remove sorting for the Question column as it sorts entries based on the ID (instead of the text): 


2. There is no question text to display in the Conditions section on the Split position/Report payouts page


3. Just a bit weird, but search by 'Why' (when select Question text option) returns no values


however, they exist:


4. Question text is not displayed for several conditions, however, it exists in condition details pages


I think, it would be nice to consider these cases before deployment the functionality to dev.

**Comment by mariano-aguero** [comment]
I will close this pull request, is outdated, and probably some things will not exist anymore

**Pull request closed without merging**
