### PR TITLE
(fix) Cookies banner for the built app

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Addresses https://github.com/gnosis/conditional-tokens-explorer/issues/300#issuecomment-697459009

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr324--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr324--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
Looks good to me

**Comment by gabitoesmiapodo** [comment]
@elena-zh OK, please approve it so I can merge the PR.

**Review by elena-zh — APPROVED** [review]

**Comment by elena-zh** [comment]
Done

**Pull request merged**
