### PR TITLE
(Feature) Remove or disable selected conditions / positions

### LINKED ISSUE #201: [FE] Remove selected items from list
_"Select Position"_ items should be removed when selected. It makes no sense to have them there when already selected.

The same should occur with _"Select Condition"_ items, even if the user is selecting only one.

In case this is extremely complicated, we should at least disable already selected items.

Conditional_Tokens_Explorer_And_Factory-2

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #201 

This opts for filter out selected positions/conditions from the list.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr386--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — APPROVED** [review]
It does what it says it does.

Theres a blink / flash when selecting positions, is it possible to avoid it?

**Comment by hpmaxi** [comment]
> Theres a blink / flash when selecting positions, is it possible to avoid it?

@gabitoesmiapodo 
There are two options, one is to disable rows instead of removing them when you select a position and the other is to add cache logic to token icon / symbol / decimal logic. I didn't found another possible reason for that extra time between renders.

**Comment by gabitoesmiapodo** [comment]
@hpmaxi I think removing the items (as it is now) is better than disabling them... so it seems this would need some extra work to fix the blinking.

It's just an enhancement, not really needed now, so I'll create an issue about that.

**Review by mariano-aguero — APPROVED** [review]

**Pull request merged**
