### PR TITLE
Add spinner  while outcomes load

### LINKED ISSUE #753: [FE] Add spinner to Outcomes Collections table in "Split position" page
It seems in some cases there's a noticeable lag when the user clicks on a condition and up to the moment the outcomes collection section is updated:
https://drive.google.com/file/d/1CzmRjgl8e4qLpzqOPHKOQ5f4crysm0hw/view
In my case I had several conditions with many outcomes, so it may have something to do with that.
We could add a spinner to let the users know that something's going on.

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #753 

This has something for #543 

Look like this. For long outcomes names, I think we should use only the id inside the circle and value by the side. 
Captura de pantalla de 2021-01-18 18-10-21
Captura de pantalla de 2021-01-18 18-10-29

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr801--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — CHANGES_REQUESTED** [review]
Hmm, nope.

You should use the little circles only to display outcomes' numbers (that's the only thing we had when we implemented this). You should display any extra information using the tooltips. In this case that's the outcomes' text, I assume. 

**Something like:**

**Outcome:** So and so.
**ID:** 0x1234...5678 [maybe the copy button]

_MAYBE_ (and that's a big _maybe_) we could just display the text  if there's only one outcome per row, but I guess that will complicate things unnecessarily. We could improve this later: we should find a nice way to show the outcomes' text, the outcomes' relationships in collections, etc.

Also, the question should be displayed as we display it everywhere else (not below the "Outcomes collections" text). Use the oddly named `TitleValue` component:

Conditional_Tokens_Explorer_And_Factory

I think that placing the question just before the partition block makes the most sense.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr801--conditionaltokensexplorer.review.gnosisdev.com

**Comment by hpmaxi** [comment]
Captura de pantalla de 2021-01-19 10-32-59

I've just moved question text outside the circle to the tooltip in use, seems like a little hidden at first sight so I guess I'm using badly the current UI components, but also I think that something bigger can be annoying at the moment of drag&drop in the edit partition section.

**Comment by elena-zh** [comment]
Hi @hpmaxi , 
I have just reviewed the changes, and they look good to me. 
However, there is one question from my side. Look:  I can create a Custom Reporter condition with a lot of outcomes, and 'borrow' a question ID from an Omen condition there. As a result, I get a custom reporter condition with a question text. The first outcomes in the list  show the answers from the Omen condition, the rest ones show simple id. The question is:  Is that okay that outcomes from an omen condition are transferred along with the question text into the custom reporter condition?


Here is an example of such condition id: 0x49e7b05dcd1d5f873f6f37dfea9a33eeb278502112383eda8dbe603f8af339be

**Comment by hpmaxi** [comment]
> I can create a Custom Reporter condition with a lot of outcomes, and 'borrow' a question ID from an Omen condition there. As a result, I get a custom reporter condition with a question text. The first outcomes in the list show the answers from the Omen condition, the rest ones show simple id. The question is: Is that okay that outcomes from an omen condition are transferred along with the question text into the custom reporter condition?

Good catch!. I will create an issue in the graph.

**Comment by gabitoesmiapodo** [comment]
Looks better.

I'd suggest you use the format:

Id: 2134
Value: Outcome text.

You can use HTML for the tooltips' content.

I think in the future we could go for badges or something like that instead of circles, but that's what we have available now.

**Comment by hpmaxi** [comment]
@gabitoesmiapodo thanks for the feedback. I made some changes as in the screenshots (id and value are capitalized in the last version). I tried to make some styled-components with other font-family, font-weight, etc. but it didn't work inside the tootip.

Captura de pantalla de 2021-01-20 17-09-19
Captura de pantalla de 2021-01-20 17-09-24

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr801--conditionaltokensexplorer.review.gnosisdev.com

**Review by gabitoesmiapodo — APPROVED** [review]
@hpmaxi 

That's fine, it looks nice now.

We'll keep improving it later.

**Review by mariano-aguero — APPROVED** [review]

**Pull request merged**
